// Copyright 2021 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from action_msgs/msg/GoalInfo.msg - do not modify

#pragma once

#include <CoreMinimal.h>

#include "action_msgs/msg/goal_info.h"

#include "Msgs/ROS2GenericMsg.h"
#include "rclcUtilities.h"

#include "ROS2GoalInfoMsg.generated.h"

USTRUCT(Blueprintable)
struct RCLUE_API FROSGoalInfo
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere)
	TArray<uint8> GoalIdUuid;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	int StampSec = 0;

	UPROPERTY(EditAnywhere)
	unsigned int StampNanosec = 0;

	

	void SetFromROS2(const action_msgs__msg__GoalInfo& in_ros_data)
	{
    	for (auto i = 0; i < 16; ++i)
		{
			GoalIdUuid.Emplace(in_ros_data.goal_id.uuid[i]);
		}

		StampSec = in_ros_data.stamp.sec;

		StampNanosec = in_ros_data.stamp.nanosec;

		
	}

	void SetROS2(action_msgs__msg__GoalInfo& out_ros_data) const
	{
    	for (auto i = 0; i < 16; ++i)
		{
			out_ros_data.goal_id.uuid[i] = GoalIdUuid[i];
		}

		out_ros_data.stamp.sec = StampSec;

		out_ros_data.stamp.nanosec = StampNanosec;

		
	}
};

UCLASS()
class RCLUE_API UROS2GoalInfoMsg : public UROS2GenericMsg
{
	GENERATED_BODY()

public:
	virtual void Init() override;
	virtual void Fini() override;

	virtual const rosidl_message_type_support_t* GetTypeSupport() const override;
	
  	UFUNCTION(BlueprintCallable)
	void SetMsg(const FROSGoalInfo& Input);
	
  	UFUNCTION(BlueprintCallable)
	void GetMsg(FROSGoalInfo& Output) const;
	
	virtual void* Get() override;

private:
	virtual FString MsgToString() const override;

	action_msgs__msg__GoalInfo goal_info_msg;
};