// Copyright 2021 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from sensor_msgs/msg/NavSatFix.msg - do not modify

#pragma once

#include <CoreMinimal.h>

#include "sensor_msgs/msg/nav_sat_fix.h"

#include "Msgs/ROS2GenericMsg.h"
#include "rclcUtilities.h"

#include "ROS2NavSatFixMsg.generated.h"

USTRUCT(Blueprintable)
struct RCLUE_API FROSNavSatFix
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	int HeaderStampSec = 0;

	UPROPERTY(EditAnywhere)
	unsigned int HeaderStampNanosec = 0;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FString HeaderFrameId;

	UPROPERTY(EditAnywhere)
	int8 StatusStatus = 0;

	UPROPERTY(EditAnywhere)
	uint16 StatusService = 0;

	UPROPERTY(EditAnywhere)
	double Latitude = 0.f;

	UPROPERTY(EditAnywhere)
	double Longitude = 0.f;

	UPROPERTY(EditAnywhere)
	double Altitude = 0.f;

	UPROPERTY(EditAnywhere)
	TArray<double> PositionCovariance;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	uint8 PositionCovarianceType = 0;

	

	void SetFromROS2(const sensor_msgs__msg__NavSatFix& in_ros_data)
	{
    	HeaderStampSec = in_ros_data.header.stamp.sec;

		HeaderStampNanosec = in_ros_data.header.stamp.nanosec;

		HeaderFrameId.AppendChars(in_ros_data.header.frame_id.data, in_ros_data.header.frame_id.size);

		StatusStatus = in_ros_data.status.status;

		StatusService = in_ros_data.status.service;

		Latitude = in_ros_data.latitude;

		Longitude = in_ros_data.longitude;

		Altitude = in_ros_data.altitude;

		for (auto i = 0; i < 9; ++i)
		{
			PositionCovariance.Emplace(in_ros_data.position_covariance[i]);
		}

		PositionCovarianceType = in_ros_data.position_covariance_type;

		
	}

	void SetROS2(sensor_msgs__msg__NavSatFix& out_ros_data) const
	{
    	out_ros_data.header.stamp.sec = HeaderStampSec;

		out_ros_data.header.stamp.nanosec = HeaderStampNanosec;

		{
			FTCHARToUTF8 strUtf8( *HeaderFrameId );
			int32 strLength = strUtf8.Length();
			if (out_ros_data.header.frame_id.data != nullptr)
		{
			free(out_ros_data.header.frame_id.data);
		}
		out_ros_data.header.frame_id.data = (decltype(out_ros_data.header.frame_id.data))malloc((strLength+1)*sizeof(decltype(*out_ros_data.header.frame_id.data)));
		memcpy(out_ros_data.header.frame_id.data, TCHAR_TO_UTF8(*HeaderFrameId), (strLength+1)*sizeof(char));
			out_ros_data.header.frame_id.size = strLength;
			out_ros_data.header.frame_id.capacity = strLength + 1;
		}

		out_ros_data.status.status = StatusStatus;

		out_ros_data.status.service = StatusService;

		out_ros_data.latitude = Latitude;

		out_ros_data.longitude = Longitude;

		out_ros_data.altitude = Altitude;

		for (auto i = 0; i < 9; ++i)
		{
			out_ros_data.position_covariance[i] = PositionCovariance[i];
		}

		out_ros_data.position_covariance_type = PositionCovarianceType;

		
	}
};

UCLASS()
class RCLUE_API UROS2NavSatFixMsg : public UROS2GenericMsg
{
	GENERATED_BODY()

public:
	virtual void Init() override;
	virtual void Fini() override;

	virtual const rosidl_message_type_support_t* GetTypeSupport() const override;
	
  	UFUNCTION(BlueprintCallable)
	void SetMsg(const FROSNavSatFix& Input);
	
  	UFUNCTION(BlueprintCallable)
	void GetMsg(FROSNavSatFix& Output) const;
	
	virtual void* Get() override;

private:
	virtual FString MsgToString() const override;

	sensor_msgs__msg__NavSatFix nav_sat_fix_msg;
};