// Copyright 2021 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from example_interfaces/UInt16.msg - do not modify

#pragma once

#include <CoreMinimal.h>

#include "example_interfaces/msg/u_int16.h"

#include "Msgs/ROS2GenericMsg.h"
#include "rclcUtilities.h"

#include "ROS2UInt16Msg.generated.h"

USTRUCT(Blueprintable)
struct RCLUE_API FROSUInt16
{
	GENERATED_BODY()

public:
	uint16 data;

	

	void SetFromROS2(const example_interfaces__msg__UInt16& in_ros_data)
	{
    	data = in_ros_data.data;

		
	}

	void SetROS2(example_interfaces__msg__UInt16& out_ros_data) const
	{
    	out_ros_data.data = data;

		
	}
};

UCLASS()
class RCLUE_API UROS2UInt16Msg : public UROS2GenericMsg
{
	GENERATED_BODY()

public:
	virtual void Init() override;
	virtual void Fini() override;

	virtual const rosidl_message_type_support_t* GetTypeSupport() const override;
	
  	UFUNCTION(BlueprintCallable)
	void SetMsg(const FROSUInt16& Input);
	
  	UFUNCTION(BlueprintCallable)
	void GetMsg(FROSUInt16& Output) const;
	
	virtual void* Get() override;

private:
	virtual FString MsgToString() const override;

	example_interfaces__msg__UInt16 u_int16_msg;
};