// Copyright 2021 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from geometry_msgs/Twist.msg - do not modify

#pragma once

#include "CoreMinimal.h"

#include "geometry_msgs/msg/twist.h"

#include "Msgs/ROS2GenericMsg.h"
#include "rclcUtilities.h"

#include "ROS2TwistMsg.generated.h"

USTRUCT(Blueprintable)
struct RCLUE_API FROSTwist
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FVector linear;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FVector angular;

	

	void SetFromROS2(geometry_msgs__msg__Twist rosdata)
	{
    	linear.X = rosdata.linear.x;
		linear.Y = rosdata.linear.y;
		linear.Z = rosdata.linear.z;

		angular.X = rosdata.angular.x;
		angular.Y = rosdata.angular.y;
		angular.Z = rosdata.angular.z;

		
	}

	void SetROS2(geometry_msgs__msg__Twist& rosdata) const
	{
    	rosdata.linear.x = linear.X;
		rosdata.linear.y = linear.Y;
		rosdata.linear.z = linear.Z;

		rosdata.angular.x = angular.X;
		rosdata.angular.y = angular.Y;
		rosdata.angular.z = angular.Z;

		
	}
};

UCLASS()
class RCLUE_API UROS2TwistMsg : public UROS2GenericMsg
{
	GENERATED_BODY()

public:
	virtual void Init() override;
	virtual void Fini() override;

	virtual const rosidl_message_type_support_t* GetTypeSupport() const override;
	
  	UFUNCTION(BlueprintCallable)
	void SetMsg(const FROSTwist Input);
	
  	UFUNCTION(BlueprintCallable)
	void GetMsg(FROSTwist& Output);
	
	virtual void* Get() override;

private:
	virtual FString MsgToString() const override;

	geometry_msgs__msg__Twist twist_msg;
};