// Copyright 2021 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from geometry_msgs/msg/Polygon.msg - do not modify

#pragma once

#include <CoreMinimal.h>

#include "geometry_msgs/msg/polygon.h"

#include "Msgs/ROS2GenericMsg.h"
#include "rclcUtilities.h"

#include "ROS2PolygonMsg.generated.h"

USTRUCT(Blueprintable)
struct RCLUE_API FROSPolygon
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	TArray<FVector> Points;

	

	void SetFromROS2(const geometry_msgs__msg__Polygon& in_ros_data)
	{
    	for (auto i = 0; i < in_ros_data.points.size; ++i)
		{
			Points.Emplace(FVector::ZeroVector);
			Points[i].X = in_ros_data.points.data[i].x;
			Points[i].Y = in_ros_data.points.data[i].y;
			Points[i].Z = in_ros_data.points.data[i].z;
		}

		
	}

	void SetROS2(geometry_msgs__msg__Polygon& out_ros_data) const
	{
    	if (out_ros_data.points.data != nullptr)
		{
			free(out_ros_data.points.data);
		}
		out_ros_data.points.data = (decltype(out_ros_data.points.data))malloc((Points.Num() * 3)*sizeof(decltype(*out_ros_data.points.data)));
		
		for (auto i = 0; i < Points.Num(); ++i)
		{
			out_ros_data.points.data[i].x = Points[i].X;
			out_ros_data.points.data[i].y = Points[i].Y;
			out_ros_data.points.data[i].z = Points[i].Z;
		}

		out_ros_data.points.size = Points.Num();
		out_ros_data.points.capacity = Points.Num();

		
	}
};

UCLASS()
class RCLUE_API UROS2PolygonMsg : public UROS2GenericMsg
{
	GENERATED_BODY()

public:
	virtual void Init() override;
	virtual void Fini() override;

	virtual const rosidl_message_type_support_t* GetTypeSupport() const override;
	
  	UFUNCTION(BlueprintCallable)
	void SetMsg(const FROSPolygon& Input);
	
  	UFUNCTION(BlueprintCallable)
	void GetMsg(FROSPolygon& Output) const;
	
	virtual void* Get() override;

private:
	virtual FString MsgToString() const override;

	geometry_msgs__msg__Polygon polygon_msg;
};