// Copyright 2021 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from shape_msgs/msg/Mesh.msg - do not modify

#pragma once

// UE
#include <CoreMinimal.h>

// ROS
#include "shape_msgs/msg/mesh.h"

// rclUE
#include "Msgs/ROS2GenericMsg.h"
#include "rclcUtilities.h"

// Generated Msg/Srv/Action(can be empty)
#include "Msgs/ROS2MeshTriangle.h"

// Generated
#include "ROS2Mesh.generated.h"

USTRUCT(Blueprintable)
struct RCLUE_API FROSMesh {
  GENERATED_BODY()

public:
  UPROPERTY(EditAnywhere, BlueprintReadWrite)
  TArray<FROSMeshTriangle> Triangles;

  UPROPERTY(EditAnywhere, BlueprintReadWrite)
  TArray<FVector> Vertices;

  FROSMesh() {}

  void SetFromROS2(const shape_msgs__msg__Mesh &in_ros_data) {
    for (auto i = 0; i < in_ros_data.triangles.size; ++i) {
      Triangles[i].SetFromROS2(in_ros_data.triangles.data[i]);
    }

    for (auto i = 0; i < in_ros_data.vertices.size; ++i) {
      Vertices.Emplace(FVector::ZeroVector);
      Vertices[i].X = in_ros_data.vertices.data[i].x;
      Vertices[i].Y = in_ros_data.vertices.data[i].y;
      Vertices[i].Z = in_ros_data.vertices.data[i].z;
    }
  }

  void SetROS2(shape_msgs__msg__Mesh &out_ros_data) const {
    out_ros_data.triangles.data = (decltype(out_ros_data.triangles.data))malloc(
        (Triangles.Num()) * sizeof(decltype(*out_ros_data.triangles.data)));

    for (auto i = 0; i < Triangles.Num(); ++i) {
      Triangles[i].SetROS2(out_ros_data.triangles.data[i]);
    }

    out_ros_data.triangles.size = Triangles.Num();
    out_ros_data.triangles.capacity = Triangles.Num();

    out_ros_data.vertices.data = (decltype(out_ros_data.vertices.data))malloc(
        (Vertices.Num() * 3) * sizeof(decltype(*out_ros_data.vertices.data)));

    for (auto i = 0; i < Vertices.Num(); ++i) {
      out_ros_data.vertices.data[i].x = Vertices[i].X;
      out_ros_data.vertices.data[i].y = Vertices[i].Y;
      out_ros_data.vertices.data[i].z = Vertices[i].Z;
    }

    out_ros_data.vertices.size = Vertices.Num();
    out_ros_data.vertices.capacity = Vertices.Num();
  }
};

UCLASS()
class RCLUE_API UROS2MeshMsg : public UROS2GenericMsg {
  GENERATED_BODY()

public:
  virtual void Init() override;
  virtual void Fini() override;

  virtual const rosidl_message_type_support_t *GetTypeSupport() const override;

  UFUNCTION(BlueprintCallable)
  void SetMsg(const FROSMesh &Input);

  UFUNCTION(BlueprintCallable)
  void GetMsg(FROSMesh &Output) const;

  virtual void *Get() override;

private:
  virtual FString MsgToString() const override;

  shape_msgs__msg__Mesh mesh_msg;
};