// Copyright 2021 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from sensor_msgs/NavSatFix.msg - do not modify

#pragma once

#include "CoreMinimal.h"

#include "sensor_msgs/msg/nav_sat_fix.h"

#include "Msgs/ROS2GenericMsg.h"
#include "rclcUtilities.h"

#include "ROS2NavSatFixMsg.generated.h"

USTRUCT(Blueprintable)
struct RCLUE_API FROSNavSatFix
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	int header_stamp_sec;

	unsigned int header_stamp_nanosec;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FString header_frame_id;

	int8 status_status;

	uint16 status_service;

	double latitude;

	double longitude;

	double altitude;

	TArray<double> position_covariance;

	uint8 position_covariance_type;

	

	void SetFromROS2(sensor_msgs__msg__NavSatFix rosdata)
	{
    	header_stamp_sec = rosdata.header.stamp.sec;

		header_stamp_nanosec = rosdata.header.stamp.nanosec;

		header_frame_id.AppendChars(rosdata.header.frame_id.data, rosdata.header.frame_id.size);

		status_status = rosdata.status.status;

		status_service = rosdata.status.service;

		latitude = rosdata.latitude;

		longitude = rosdata.longitude;

		altitude = rosdata.altitude;

		for (int i = 0; i < 9; i++)
		{
			position_covariance[i] = rosdata.position_covariance[i];
		}

		position_covariance_type = rosdata.position_covariance_type;

		
	}

	void SetROS2(sensor_msgs__msg__NavSatFix& rosdata) const
	{
    	rosdata.header.stamp.sec = header_stamp_sec;

		rosdata.header.stamp.nanosec = header_stamp_nanosec;

		if (rosdata.header.frame_id.data != nullptr)
		{
			free(rosdata.header.frame_id.data);
		}
		rosdata.header.frame_id.data = (char*)malloc((header_frame_id.Len()+1)*sizeof(char));
		memcpy(rosdata.header.frame_id.data, TCHAR_TO_ANSI(*header_frame_id), (header_frame_id.Len()+1)*sizeof(char));
		rosdata.header.frame_id.size = header_frame_id.Len();
		rosdata.header.frame_id.capacity = header_frame_id.Len() + 1;

		rosdata.status.status = status_status;

		rosdata.status.service = status_service;

		rosdata.latitude = latitude;

		rosdata.longitude = longitude;

		rosdata.altitude = altitude;

		for (int i = 0; i < 9; i++)
		{
			rosdata.position_covariance[i] = position_covariance[i];
		}

		rosdata.position_covariance_type = position_covariance_type;

		
	}
};

UCLASS()
class RCLUE_API UROS2NavSatFixMsg : public UROS2GenericMsg
{
	GENERATED_BODY()

public:
	virtual void Init() override;
	virtual void Fini() override;

	virtual const rosidl_message_type_support_t* GetTypeSupport() const override;
	
  	UFUNCTION(BlueprintCallable)
	void SetMsg(const FROSNavSatFix Input);
	
  	UFUNCTION(BlueprintCallable)
	void GetMsg(FROSNavSatFix& Output);
	
	virtual void* Get() override;

private:
	virtual FString MsgToString() const override;

	sensor_msgs__msg__NavSatFix nav_sat_fix_msg;
};