// Copyright 2021 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from geometry_msgs/msg/Twist.msg - do not
// modify

#pragma once

// UE
#include <CoreMinimal.h>

// ROS
#include "geometry_msgs/msg/twist.h"

// rclUE
#include "Msgs/ROS2GenericMsg.h"
#include "rclcUtilities.h"

// Generated Msg/Srv/Action(can be empty)

// Generated
#include "ROS2Twist.generated.h"

USTRUCT(Blueprintable)
struct RCLUE_API FROSTwist {
  GENERATED_BODY()

public:
  UPROPERTY(EditAnywhere, BlueprintReadWrite)
  FVector Linear = FVector::ZeroVector;

  UPROPERTY(EditAnywhere, BlueprintReadWrite)
  FVector Angular = FVector::ZeroVector;

  FROSTwist() {}

  void SetFromROS2(const geometry_msgs__msg__Twist &in_ros_data) {
    Linear.X = in_ros_data.linear.x;
    Linear.Y = in_ros_data.linear.y;
    Linear.Z = in_ros_data.linear.z;

    Angular.X = in_ros_data.angular.x;
    Angular.Y = in_ros_data.angular.y;
    Angular.Z = in_ros_data.angular.z;
  }

  void SetROS2(geometry_msgs__msg__Twist &out_ros_data) const {
    out_ros_data.linear.x = Linear.X;
    out_ros_data.linear.y = Linear.Y;
    out_ros_data.linear.z = Linear.Z;

    out_ros_data.angular.x = Angular.X;
    out_ros_data.angular.y = Angular.Y;
    out_ros_data.angular.z = Angular.Z;
  }
};

UCLASS()
class RCLUE_API UROS2TwistMsg : public UROS2GenericMsg {
  GENERATED_BODY()

public:
  virtual void Init() override;
  virtual void Fini() override;

  virtual const rosidl_message_type_support_t *GetTypeSupport() const override;

  UFUNCTION(BlueprintCallable)
  void SetMsg(const FROSTwist &Input);

  UFUNCTION(BlueprintCallable)
  void GetMsg(FROSTwist &Output) const;

  virtual void *Get() override;

private:
  virtual FString MsgToString() const override;

  geometry_msgs__msg__Twist twist_msg;
};