// Copyright 2021 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from sensor_msgs/NavSatFix.msg - do not modify

#pragma once

#include <CoreMinimal.h>

#include "sensor_msgs/msg/nav_sat_fix.h"

#include "Msgs/ROS2GenericMsg.h"
#include "Msgs/ROS2HeaderMsg.h"
#include "Msgs/ROS2NavSatStatusMsg.h"
#include "rclcUtilities.h"

#include "ROS2NavSatFixMsg.generated.h"

UENUM(BlueprintType)
enum class UROSNavSatFixPositionCovarianceType : uint8
{
	COVARIANCE_TYPE_UNKNOWN = 0,
	COVARIANCE_TYPE_APPROXIMATED = 1,
	COVARIANCE_TYPE_DIAGONAL_KNOWN = 2,
	COVARIANCE_TYPE_KNOWN = 3
};

USTRUCT(Blueprintable)
struct RCLUE_API FROSNavSatFix
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FROSHeader header;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FROSNavSatStatus status;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	float latitude; // original double

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	float longitude; // original double

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	float altitude; // original double

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	TArray<float> position_covariance = ArrayInitialisers::FloatArray(9); // original double
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	UROSNavSatFixPositionCovarianceType position_covariance_type; // original uint8


	void SetFromROS2(const sensor_msgs__msg__NavSatFix& in_ros_data)
	{
    	header.SetFromROS2(in_ros_data.header);
		status.SetFromROS2(in_ros_data.status);
		latitude = in_ros_data.latitude;
		longitude = in_ros_data.longitude;
		altitude = in_ros_data.altitude;
		position_covariance = ROS2MsgToUE::FromArray(in_ros_data.position_covariance);
		position_covariance_type = static_cast<UROSNavSatFixPositionCovarianceType>(in_ros_data.position_covariance_type);
	}

	void SetROS2(sensor_msgs__msg__NavSatFix& out_ros_data) const
	{
		header.SetROS2(out_ros_data.header);
		status.SetROS2(out_ros_data.status);
		out_ros_data.latitude = latitude;
		out_ros_data.longitude = longitude;
		out_ros_data.altitude = altitude;
		UEToROS2Msg::SetSequence(position_covariance, out_ros_data.position_covariance);
		out_ros_data.position_covariance_type = static_cast<uint8>(position_covariance_type);
	}
};

UCLASS()
class RCLUE_API UROS2NavSatFixMsg : public UROS2GenericMsg
{
	GENERATED_BODY()

public:
	virtual void Init() override;
	virtual void Fini() override;

	virtual const rosidl_message_type_support_t* GetTypeSupport() const override;
	
  	UFUNCTION(BlueprintCallable)
	void SetMsg(const FROSNavSatFix& Input);
	
  	UFUNCTION(BlueprintCallable)
	void GetMsg(FROSNavSatFix& Output) const;
	
	virtual void* Get() override;

private:
	virtual FString MsgToString() const override;

	sensor_msgs__msg__NavSatFix nav_sat_fix_msg;
};