// Copyright 2021 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from sensor_msgs/MagneticField.msg - do not modify

#pragma once

#include "CoreMinimal.h"

#include "sensor_msgs/msg/magnetic_field.h"

#include "Msgs/ROS2GenericMsg.h"
#include "rclcUtilities.h"

#include "ROS2MagneticFieldMsg.generated.h"

USTRUCT(Blueprintable)
struct RCLUE_API FROSMagneticField
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	int header_stamp_sec;

	unsigned int header_stamp_nanosec;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FString header_frame_id;

	double magnetic_field_x;

	double magnetic_field_y;

	double magnetic_field_z;

	TArray<double> magnetic_field_covariance;

	

	void SetFromROS2(sensor_msgs__msg__MagneticField rosdata)
	{
    	header_stamp_sec = rosdata.header.stamp.sec;

		header_stamp_nanosec = rosdata.header.stamp.nanosec;

		header_frame_id.AppendChars(rosdata.header.frame_id.data, rosdata.header.frame_id.size);

		magnetic_field_x = rosdata.magnetic_field.x;

		magnetic_field_y = rosdata.magnetic_field.y;

		magnetic_field_z = rosdata.magnetic_field.z;

		for (int i = 0; i < 9; i++)
		{
			magnetic_field_covariance[i] = rosdata.magnetic_field_covariance[i];
		}

		
	}

	void SetROS2(sensor_msgs__msg__MagneticField& rosdata) const
	{
    	rosdata.header.stamp.sec = header_stamp_sec;

		rosdata.header.stamp.nanosec = header_stamp_nanosec;

		if (rosdata.header.frame_id.data != nullptr)
		{
			free(rosdata.header.frame_id.data);
		}
		rosdata.header.frame_id.data = (char*)malloc((header_frame_id.Len()+1)*sizeof(char));
		memcpy(rosdata.header.frame_id.data, TCHAR_TO_ANSI(*header_frame_id), (header_frame_id.Len()+1)*sizeof(char));
		rosdata.header.frame_id.size = header_frame_id.Len();
		rosdata.header.frame_id.capacity = header_frame_id.Len() + 1;

		rosdata.magnetic_field.x = magnetic_field_x;

		rosdata.magnetic_field.y = magnetic_field_y;

		rosdata.magnetic_field.z = magnetic_field_z;

		for (int i = 0; i < 9; i++)
		{
			rosdata.magnetic_field_covariance[i] = magnetic_field_covariance[i];
		}

		
	}
};

UCLASS()
class RCLUE_API UROS2MagneticFieldMsg : public UROS2GenericMsg
{
	GENERATED_BODY()

public:
	virtual void Init() override;
	virtual void Fini() override;

	virtual const rosidl_message_type_support_t* GetTypeSupport() const override;
	
  	UFUNCTION(BlueprintCallable)
	void SetMsg(const FROSMagneticField Input);
	
  	UFUNCTION(BlueprintCallable)
	void GetMsg(FROSMagneticField& Output);
	
	virtual void* Get() override;

private:
	virtual FString MsgToString() const override;

	sensor_msgs__msg__MagneticField magnetic_field_msg;
};