// Copyright 2021 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from nav_msgs/msg/MapMetaData.msg - do not modify

#pragma once

#include <CoreMinimal.h>

#include "nav_msgs/msg/map_meta_data.h"

#include "Msgs/ROS2GenericMsg.h"
#include "rclcUtilities.h"

#include "ROS2MapMetaDataMsg.generated.h"

USTRUCT(Blueprintable)
struct RCLUE_API FROSMapMetaData
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	int MapLoadTimeSec = 0;

	UPROPERTY(EditAnywhere)
	unsigned int MapLoadTimeNanosec = 0;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	float Resolution = 0.f;

	UPROPERTY(EditAnywhere)
	unsigned int Width = 0;

	UPROPERTY(EditAnywhere)
	unsigned int Height = 0;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FVector OriginPosition = FVector::ZeroVector;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FQuat OriginOrientation = FQuat::Identity;

	

	void SetFromROS2(const nav_msgs__msg__MapMetaData& in_ros_data)
	{
    	MapLoadTimeSec = in_ros_data.map_load_time.sec;

		MapLoadTimeNanosec = in_ros_data.map_load_time.nanosec;

		Resolution = in_ros_data.resolution;

		Width = in_ros_data.width;

		Height = in_ros_data.height;

		OriginPosition.X = in_ros_data.origin.position.x;
		OriginPosition.Y = in_ros_data.origin.position.y;
		OriginPosition.Z = in_ros_data.origin.position.z;

		OriginOrientation.X = in_ros_data.origin.orientation.x;
		OriginOrientation.Y = in_ros_data.origin.orientation.y;
		OriginOrientation.Z = in_ros_data.origin.orientation.z;
		OriginOrientation.W = in_ros_data.origin.orientation.w;

		
	}

	void SetROS2(nav_msgs__msg__MapMetaData& out_ros_data) const
	{
    	out_ros_data.map_load_time.sec = MapLoadTimeSec;

		out_ros_data.map_load_time.nanosec = MapLoadTimeNanosec;

		out_ros_data.resolution = Resolution;

		out_ros_data.width = Width;

		out_ros_data.height = Height;

		out_ros_data.origin.position.x = OriginPosition.X;
		out_ros_data.origin.position.y = OriginPosition.Y;
		out_ros_data.origin.position.z = OriginPosition.Z;

		out_ros_data.origin.orientation.x = OriginOrientation.X;
		out_ros_data.origin.orientation.y = OriginOrientation.Y;
		out_ros_data.origin.orientation.z = OriginOrientation.Z;
		out_ros_data.origin.orientation.w = OriginOrientation.W;

		
	}
};

UCLASS()
class RCLUE_API UROS2MapMetaDataMsg : public UROS2GenericMsg
{
	GENERATED_BODY()

public:
	virtual void Init() override;
	virtual void Fini() override;

	virtual const rosidl_message_type_support_t* GetTypeSupport() const override;
	
  	UFUNCTION(BlueprintCallable)
	void SetMsg(const FROSMapMetaData& Input);
	
  	UFUNCTION(BlueprintCallable)
	void GetMsg(FROSMapMetaData& Output) const;
	
	virtual void* Get() override;

private:
	virtual FString MsgToString() const override;

	nav_msgs__msg__MapMetaData map_meta_data_msg;
};