// Copyright 2021 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from shape_msgs/msg/MeshTriangle.msg - do not modify

#pragma once

#include <CoreMinimal.h>

#include "shape_msgs/msg/mesh_triangle.h"

#include "Msgs/ROS2GenericMsg.h"
#include "rclcUtilities.h"

#include "ROS2MeshTriangleMsg.generated.h"

USTRUCT(Blueprintable)
struct RCLUE_API FROSMeshTriangle
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere)
	TArray<unsigned int> VertexIndices;

	

	void SetFromROS2(const shape_msgs__msg__MeshTriangle& in_ros_data)
	{
    	for (auto i = 0; i < 3; ++i)
		{
			VertexIndices.Emplace(in_ros_data.vertex_indices[i]);
		}

		
	}

	void SetROS2(shape_msgs__msg__MeshTriangle& out_ros_data) const
	{
    	for (auto i = 0; i < 3; ++i)
		{
			out_ros_data.vertex_indices[i] = VertexIndices[i];
		}

		
	}
};

UCLASS()
class RCLUE_API UROS2MeshTriangleMsg : public UROS2GenericMsg
{
	GENERATED_BODY()

public:
	virtual void Init() override;
	virtual void Fini() override;

	virtual const rosidl_message_type_support_t* GetTypeSupport() const override;
	
  	UFUNCTION(BlueprintCallable)
	void SetMsg(const FROSMeshTriangle& Input);
	
  	UFUNCTION(BlueprintCallable)
	void GetMsg(FROSMeshTriangle& Output) const;
	
	virtual void* Get() override;

private:
	virtual FString MsgToString() const override;

	shape_msgs__msg__MeshTriangle mesh_triangle_msg;
};