// Copyright 2021 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from geometry_msgs/msg/TransformStamped.msg - do not modify

#pragma once

#include <CoreMinimal.h>

#include "geometry_msgs/msg/transform_stamped.h"

#include "Msgs/ROS2GenericMsg.h"
#include "rclcUtilities.h"

#include "ROS2TransformStampedMsg.generated.h"

USTRUCT(Blueprintable)
struct RCLUE_API FROSTransformStamped
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	int HeaderStampSec = 0;

	UPROPERTY(EditAnywhere)
	unsigned int HeaderStampNanosec = 0;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FString HeaderFrameId;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FString ChildFrameId;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FVector TransformTranslation = FVector::ZeroVector;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FQuat TransformRotation = FQuat::Identity;

	

	void SetFromROS2(const geometry_msgs__msg__TransformStamped& in_ros_data)
	{
    	HeaderStampSec = in_ros_data.header.stamp.sec;

		HeaderStampNanosec = in_ros_data.header.stamp.nanosec;

		HeaderFrameId.AppendChars(in_ros_data.header.frame_id.data, in_ros_data.header.frame_id.size);

		ChildFrameId.AppendChars(in_ros_data.child_frame_id.data, in_ros_data.child_frame_id.size);

		TransformTranslation.X = in_ros_data.transform.translation.x;
		TransformTranslation.Y = in_ros_data.transform.translation.y;
		TransformTranslation.Z = in_ros_data.transform.translation.z;

		TransformRotation.X = in_ros_data.transform.rotation.x;
		TransformRotation.Y = in_ros_data.transform.rotation.y;
		TransformRotation.Z = in_ros_data.transform.rotation.z;
		TransformRotation.W = in_ros_data.transform.rotation.w;

		
	}

	void SetROS2(geometry_msgs__msg__TransformStamped& out_ros_data) const
	{
    	out_ros_data.header.stamp.sec = HeaderStampSec;

		out_ros_data.header.stamp.nanosec = HeaderStampNanosec;

		{
			FTCHARToUTF8 strUtf8( *HeaderFrameId );
			int32 strLength = strUtf8.Length();
			if (out_ros_data.header.frame_id.data != nullptr)
		{
			free(out_ros_data.header.frame_id.data);
		}
		out_ros_data.header.frame_id.data = (decltype(out_ros_data.header.frame_id.data))malloc((strLength+1)*sizeof(decltype(*out_ros_data.header.frame_id.data)));
		memcpy(out_ros_data.header.frame_id.data, TCHAR_TO_UTF8(*HeaderFrameId), (strLength+1)*sizeof(char));
			out_ros_data.header.frame_id.size = strLength;
			out_ros_data.header.frame_id.capacity = strLength + 1;
		}

		{
			FTCHARToUTF8 strUtf8( *ChildFrameId );
			int32 strLength = strUtf8.Length();
			if (out_ros_data.child_frame_id.data != nullptr)
		{
			free(out_ros_data.child_frame_id.data);
		}
		out_ros_data.child_frame_id.data = (decltype(out_ros_data.child_frame_id.data))malloc((strLength+1)*sizeof(decltype(*out_ros_data.child_frame_id.data)));
		memcpy(out_ros_data.child_frame_id.data, TCHAR_TO_UTF8(*ChildFrameId), (strLength+1)*sizeof(char));
			out_ros_data.child_frame_id.size = strLength;
			out_ros_data.child_frame_id.capacity = strLength + 1;
		}

		out_ros_data.transform.translation.x = TransformTranslation.X;
		out_ros_data.transform.translation.y = TransformTranslation.Y;
		out_ros_data.transform.translation.z = TransformTranslation.Z;

		out_ros_data.transform.rotation.x = TransformRotation.X;
		out_ros_data.transform.rotation.y = TransformRotation.Y;
		out_ros_data.transform.rotation.z = TransformRotation.Z;
		out_ros_data.transform.rotation.w = TransformRotation.W;

		
	}
};

UCLASS()
class RCLUE_API UROS2TransformStampedMsg : public UROS2GenericMsg
{
	GENERATED_BODY()

public:
	virtual void Init() override;
	virtual void Fini() override;

	virtual const rosidl_message_type_support_t* GetTypeSupport() const override;
	
  	UFUNCTION(BlueprintCallable)
	void SetMsg(const FROSTransformStamped& Input);
	
  	UFUNCTION(BlueprintCallable)
	void GetMsg(FROSTransformStamped& Output) const;
	
	virtual void* Get() override;

private:
	virtual FString MsgToString() const override;

	geometry_msgs__msg__TransformStamped transform_stamped_msg;
};