// Copyright 2021 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from geometry_msgs/TwistWithCovarianceStamped.msg - do not modify

#pragma once

#include "CoreMinimal.h"

#include "geometry_msgs/msg/twist_with_covariance_stamped.h"

#include "Msgs/ROS2GenericMsg.h"
#include "rclcUtilities.h"

#include "ROS2TwistWithCovarianceStampedMsg.generated.h"

USTRUCT(Blueprintable)
struct RCLUE_API FROSTwistWithCovarianceStamped
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	int header_stamp_sec;

	unsigned int header_stamp_nanosec;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FString header_frame_id;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FVector twist_twist_linear;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FVector twist_twist_angular;

	TArray<double> twist_covariance;

	

	void SetFromROS2(geometry_msgs__msg__TwistWithCovarianceStamped rosdata)
	{
    	header_stamp_sec = rosdata.header.stamp.sec;

		header_stamp_nanosec = rosdata.header.stamp.nanosec;

		header_frame_id.AppendChars(rosdata.header.frame_id.data, rosdata.header.frame_id.size);

		twist_twist_linear.X = rosdata.twist.twist.linear.x;
		twist_twist_linear.Y = rosdata.twist.twist.linear.y;
		twist_twist_linear.Z = rosdata.twist.twist.linear.z;

		twist_twist_angular.X = rosdata.twist.twist.angular.x;
		twist_twist_angular.Y = rosdata.twist.twist.angular.y;
		twist_twist_angular.Z = rosdata.twist.twist.angular.z;

		for (int i = 0; i < 36; i++)
		{
			twist_covariance[i] = rosdata.twist.covariance[i];
		}

		
	}

	void SetROS2(geometry_msgs__msg__TwistWithCovarianceStamped& rosdata) const
	{
    	rosdata.header.stamp.sec = header_stamp_sec;

		rosdata.header.stamp.nanosec = header_stamp_nanosec;

		if (rosdata.header.frame_id.data != nullptr)
		{
			free(rosdata.header.frame_id.data);
		}
		rosdata.header.frame_id.data = (decltype(rosdata.header.frame_id.data))malloc((header_frame_id.Len() + 1)*sizeof(decltype(*rosdata.header.frame_id.data)));
		memcpy(rosdata.header.frame_id.data, TCHAR_TO_ANSI(*header_frame_id), (header_frame_id.Len()+1)*sizeof(char));
		rosdata.header.frame_id.size = header_frame_id.Len();
		rosdata.header.frame_id.capacity = header_frame_id.Len() + 1;

		rosdata.twist.twist.linear.x = twist_twist_linear.X;
		rosdata.twist.twist.linear.y = twist_twist_linear.Y;
		rosdata.twist.twist.linear.z = twist_twist_linear.Z;

		rosdata.twist.twist.angular.x = twist_twist_angular.X;
		rosdata.twist.twist.angular.y = twist_twist_angular.Y;
		rosdata.twist.twist.angular.z = twist_twist_angular.Z;

		for (int i = 0; i < 36; i++)
		{
			rosdata.twist.covariance[i] = twist_covariance[i];
		}

		
	}
};

UCLASS()
class RCLUE_API UROS2TwistWithCovarianceStampedMsg : public UROS2GenericMsg
{
	GENERATED_BODY()

public:
	virtual void Init() override;
	virtual void Fini() override;

	virtual const rosidl_message_type_support_t* GetTypeSupport() const override;
	
  	UFUNCTION(BlueprintCallable)
	void SetMsg(const FROSTwistWithCovarianceStamped Input);
	
  	UFUNCTION(BlueprintCallable)
	void GetMsg(FROSTwistWithCovarianceStamped& Output) const;
	
	virtual void* Get() override;

private:
	virtual FString MsgToString() const override;

	geometry_msgs__msg__TwistWithCovarianceStamped twist_with_covariance_stamped_msg;
};