// Copyright 2021 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from actionlib_msgs/msg/GoalID.msg - do not
// modify

#pragma once

// UE
#include <CoreMinimal.h>

// ROS
#include "actionlib_msgs/msg/goal_id.h"

// rclUE
#include "Msgs/ROS2GenericMsg.h"
#include "rclcUtilities.h"

// Generated Msg/Srv/Action(can be empty)
#include "Msgs/ROS2Time.h"

// Generated
#include "ROS2GoalID.generated.h"

USTRUCT(Blueprintable)
struct RCLUE_API FROSGoalID {
  GENERATED_BODY()

public:
  UPROPERTY(EditAnywhere, BlueprintReadWrite)
  FROSTime Stamp;

  UPROPERTY(EditAnywhere, BlueprintReadWrite)
  FString Id;

  FROSGoalID() {}

  void SetFromROS2(const actionlib_msgs__msg__GoalID &in_ros_data) {
    Stamp.SetFromROS2(in_ros_data.stamp);

    Id.AppendChars(in_ros_data.id.data, in_ros_data.id.size);
  }

  void SetROS2(actionlib_msgs__msg__GoalID &out_ros_data) const {
    Stamp.SetROS2(out_ros_data.stamp);

    {
      FTCHARToUTF8 strUtf8(*Id);
      int32 strLength = strUtf8.Length();
      if (out_ros_data.id.data != nullptr) {
        free(out_ros_data.id.data);
      }
      out_ros_data.id.data = (decltype(out_ros_data.id.data))malloc(
          (strLength + 1) * sizeof(decltype(*out_ros_data.id.data)));
      memcpy(out_ros_data.id.data, TCHAR_TO_UTF8(*Id),
             (strLength + 1) * sizeof(char));
      out_ros_data.id.size = strLength;
      out_ros_data.id.capacity = strLength + 1;
    }
  }
};

UCLASS()
class RCLUE_API UROS2GoalIDMsg : public UROS2GenericMsg {
  GENERATED_BODY()

public:
  virtual void Init() override;
  virtual void Fini() override;

  virtual const rosidl_message_type_support_t *GetTypeSupport() const override;

  UFUNCTION(BlueprintCallable)
  void SetMsg(const FROSGoalID &Input);

  UFUNCTION(BlueprintCallable)
  void GetMsg(FROSGoalID &Output) const;

  virtual void *Get() override;

private:
  virtual FString MsgToString() const override;

  actionlib_msgs__msg__GoalID goal_id_msg;
};