// Copyright 2021 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from
// example_interfaces/msg/MultiArrayDimension.msg - do not modify

#pragma once

// UE
#include <CoreMinimal.h>

// ROS
#include "example_interfaces/msg/multi_array_dimension.h"

// rclUE
#include "Msgs/ROS2GenericMsg.h"
#include "rclcUtilities.h"

// Generated Msg/Srv/Action(can be empty)

// Generated
#include "ROS2MADim.generated.h"

USTRUCT(Blueprintable)
struct RCLUE_API FROSMADim {
  GENERATED_BODY()

public:
  UPROPERTY(EditAnywhere, BlueprintReadWrite)
  FString Label;

  UPROPERTY(EditAnywhere)
  unsigned int Size = 0;

  UPROPERTY(EditAnywhere)
  unsigned int Stride = 0;

  FROSMADim() {}

  void
  SetFromROS2(const example_interfaces__msg__MultiArrayDimension &in_ros_data) {
    Label.AppendChars(in_ros_data.label.data, in_ros_data.label.size);

    Size = in_ros_data.size;

    Stride = in_ros_data.stride;
  }

  void
  SetROS2(example_interfaces__msg__MultiArrayDimension &out_ros_data) const {
    {
      FTCHARToUTF8 strUtf8(*Label);
      int32 strLength = strUtf8.Length();
      out_ros_data.label.data = (decltype(out_ros_data.label.data))malloc(
          (strLength + 1) * sizeof(decltype(*out_ros_data.label.data)));
      memcpy(out_ros_data.label.data, TCHAR_TO_UTF8(*Label),
             (strLength + 1) * sizeof(char));
      out_ros_data.label.size = strLength;
      out_ros_data.label.capacity = strLength + 1;
    }

    out_ros_data.size = Size;

    out_ros_data.stride = Stride;
  }
};

UCLASS()
class RCLUE_API UROS2MADimMsg : public UROS2GenericMsg {
  GENERATED_BODY()

public:
  virtual void Init() override;
  virtual void Fini() override;

  virtual const rosidl_message_type_support_t *GetTypeSupport() const override;

  UFUNCTION(BlueprintCallable)
  void SetMsg(const FROSMADim &Input);

  UFUNCTION(BlueprintCallable)
  void GetMsg(FROSMADim &Output) const;

  virtual void *Get() override;

private:
  virtual FString MsgToString() const override;

  example_interfaces__msg__MultiArrayDimension multi_array_dimension_msg;
};