// Copyright 2021 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from geometry_msgs/TwistStamped.msg - do not modify

#pragma once

#include "CoreMinimal.h"

#include "geometry_msgs/msg/twist_stamped.h"

#include "Msgs/ROS2GenericMsg.h"
#include "rclcUtilities.h"

#include "ROS2TwistStampedMsg.generated.h"

USTRUCT(Blueprintable)
struct RCLUE_API FROSTwistStamped
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	int header_stamp_sec;

	unsigned int header_stamp_nanosec;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FString header_frame_id;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FVector twist_linear;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FVector twist_angular;

	

	void SetFromROS2(geometry_msgs__msg__TwistStamped rosdata)
	{
    	header_stamp_sec = rosdata.header.stamp.sec;

		header_stamp_nanosec = rosdata.header.stamp.nanosec;

		header_frame_id.AppendChars(rosdata.header.frame_id.data, rosdata.header.frame_id.size);

		twist_linear.X = rosdata.twist.linear.x;
		twist_linear.Y = rosdata.twist.linear.y;
		twist_linear.Z = rosdata.twist.linear.z;

		twist_angular.X = rosdata.twist.angular.x;
		twist_angular.Y = rosdata.twist.angular.y;
		twist_angular.Z = rosdata.twist.angular.z;

		
	}

	void SetROS2(geometry_msgs__msg__TwistStamped& rosdata) const
	{
    	rosdata.header.stamp.sec = header_stamp_sec;

		rosdata.header.stamp.nanosec = header_stamp_nanosec;

		if (rosdata.header.frame_id.data != nullptr)
		{
			free(rosdata.header.frame_id.data);
		}
		rosdata.header.frame_id.data = (char*)malloc((header_frame_id.Len()+1)*sizeof(char));
		memcpy(rosdata.header.frame_id.data, TCHAR_TO_ANSI(*header_frame_id), (header_frame_id.Len()+1)*sizeof(char));
		rosdata.header.frame_id.size = header_frame_id.Len();
		rosdata.header.frame_id.capacity = header_frame_id.Len() + 1;

		rosdata.twist.linear.x = twist_linear.X;
		rosdata.twist.linear.y = twist_linear.Y;
		rosdata.twist.linear.z = twist_linear.Z;

		rosdata.twist.angular.x = twist_angular.X;
		rosdata.twist.angular.y = twist_angular.Y;
		rosdata.twist.angular.z = twist_angular.Z;

		
	}
};

UCLASS()
class RCLUE_API UROS2TwistStampedMsg : public UROS2GenericMsg
{
	GENERATED_BODY()

public:
	virtual void Init() override;
	virtual void Fini() override;

	virtual const rosidl_message_type_support_t* GetTypeSupport() const override;
	
  	UFUNCTION(BlueprintCallable)
	void SetMsg(const FROSTwistStamped Input);
	
  	UFUNCTION(BlueprintCallable)
	void GetMsg(FROSTwistStamped& Output);
	
	virtual void* Get() override;

private:
	virtual FString MsgToString() const override;

	geometry_msgs__msg__TwistStamped twist_stamped_msg;
};