// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from std_msgs/msg/ColorRGBA.msg - do not modify

#pragma once

// UE
#include "CoreMinimal.h"

// ROS
#include "std_msgs/msg/color_rgba.h"

// rclUE
#include "Msgs/ROS2GenericMsg.h"
#include "rclcUtilities.h"

// Generated Msg/Srv/Action(can be empty)

// Generated
#include "ROS2ColorRGBA.generated.h"

USTRUCT(Blueprintable)
struct RCLUE_API FROSColorRGBA
{
    GENERATED_BODY()

public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    float R = 0.f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    float G = 0.f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    float B = 0.f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    float A = 0.f;

    FROSColorRGBA()
    {
    }

    void SetFromROS2(const std_msgs__msg__ColorRGBA& in_ros_data)
    {
        R = in_ros_data.r;

        G = in_ros_data.g;

        B = in_ros_data.b;

        A = in_ros_data.a;
    }

    void SetROS2(std_msgs__msg__ColorRGBA& out_ros_data) const
    {
        out_ros_data.r = R;

        out_ros_data.g = G;

        out_ros_data.b = B;

        out_ros_data.a = A;
    }
};

UCLASS()
class RCLUE_API UROS2ColorRGBAMsg : public UROS2GenericMsg
{
    GENERATED_BODY()

public:
    virtual void Init() override;
    virtual void Fini() override;

    virtual const rosidl_message_type_support_t* GetTypeSupport() const override;

    UFUNCTION(BlueprintCallable)
    void SetMsg(const FROSColorRGBA& Input);

    UFUNCTION(BlueprintCallable)
    void GetMsg(FROSColorRGBA& Output) const;

    virtual void* Get() override;

private:
    virtual FString MsgToString() const override;

    std_msgs__msg__ColorRGBA color_rgba_msg;
};
