// Copyright 2021 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from pcl_msgs/msg/Vertices.msg - do not
// modify

#pragma once

// UE
#include <CoreMinimal.h>

// ROS
#include "pcl_msgs/msg/vertices.h"

// rclUE
#include "Msgs/ROS2GenericMsg.h"
#include "rclcUtilities.h"

// Generated Msg/Srv/Action(can be empty)

// Generated
#include "ROS2Vertices.generated.h"

USTRUCT(Blueprintable)
struct RCLUE_API FROSVertices {
  GENERATED_BODY()

public:
  UPROPERTY(EditAnywhere)
  TArray<unsigned int> Vertices;

  FROSVertices() {}

  void SetFromROS2(const pcl_msgs__msg__Vertices &in_ros_data) {
    for (auto i = 0; i < in_ros_data.vertices.size; ++i) {
      Vertices.Emplace(in_ros_data.vertices.data[i]);
    }
  }

  void SetROS2(pcl_msgs__msg__Vertices &out_ros_data) const {
    if (out_ros_data.vertices.data != nullptr) {
      free(out_ros_data.vertices.data);
    }
    out_ros_data.vertices.data = (decltype(out_ros_data.vertices.data))malloc(
        (Vertices.Num()) * sizeof(decltype(*out_ros_data.vertices.data)));

    for (auto i = 0; i < Vertices.Num(); ++i) {
      out_ros_data.vertices.data[i] = Vertices[i];
    }

    out_ros_data.vertices.size = Vertices.Num();
    out_ros_data.vertices.capacity = Vertices.Num();
  }
};

UCLASS()
class RCLUE_API UROS2VerticesMsg : public UROS2GenericMsg {
  GENERATED_BODY()

public:
  virtual void Init() override;
  virtual void Fini() override;

  virtual const rosidl_message_type_support_t *GetTypeSupport() const override;

  UFUNCTION(BlueprintCallable)
  void SetMsg(const FROSVertices &Input);

  UFUNCTION(BlueprintCallable)
  void GetMsg(FROSVertices &Output) const;

  virtual void *Get() override;

private:
  virtual FString MsgToString() const override;

  pcl_msgs__msg__Vertices vertices_msg;
};