// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from stereo_msgs/msg/DisparityImage.msg - do not modify

#pragma once

// UE
#include "CoreMinimal.h"

// ROS
#include "stereo_msgs/msg/disparity_image.h"

// rclUE
#include "Msgs/ROS2GenericMsg.h"
#include "rclcUtilities.h"

// Generated Msg/Srv/Action(can be empty)
#include "Msgs/ROS2Header.h"
#include "Msgs/ROS2Img.h"
#include "Msgs/ROS2RegionOfInterest.h"

// Generated
#include "ROS2DisparityImg.generated.h"

USTRUCT(Blueprintable)
struct RCLUE_API FROSDisparityImg
{
    GENERATED_BODY()

public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    FROSHeader Header;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    FROSImg Image;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    float F = 0.f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    float T = 0.f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    FROSRegionOfInterest ValidWindow;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    float MinDisparity = 0.f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    float MaxDisparity = 0.f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    float DeltaD = 0.f;

    FROSDisparityImg()
    {
    }

    void SetFromROS2(const stereo_msgs__msg__DisparityImage& in_ros_data)
    {
        Header.SetFromROS2(in_ros_data.header);

        Image.SetFromROS2(in_ros_data.image);

        F = in_ros_data.f;

        T = in_ros_data.t;

        ValidWindow.SetFromROS2(in_ros_data.valid_window);

        MinDisparity = in_ros_data.min_disparity;

        MaxDisparity = in_ros_data.max_disparity;

        DeltaD = in_ros_data.delta_d;
    }

    void SetROS2(stereo_msgs__msg__DisparityImage& out_ros_data) const
    {
        Header.SetROS2(out_ros_data.header);

        Image.SetROS2(out_ros_data.image);

        out_ros_data.f = F;

        out_ros_data.t = T;

        ValidWindow.SetROS2(out_ros_data.valid_window);

        out_ros_data.min_disparity = MinDisparity;

        out_ros_data.max_disparity = MaxDisparity;

        out_ros_data.delta_d = DeltaD;
    }
};

UCLASS()
class RCLUE_API UROS2DisparityImgMsg : public UROS2GenericMsg
{
    GENERATED_BODY()

public:
    virtual void Init() override;
    virtual void Fini() override;

    virtual const rosidl_message_type_support_t* GetTypeSupport() const override;

    UFUNCTION(BlueprintCallable)
    void SetMsg(const FROSDisparityImg& Input);

    UFUNCTION(BlueprintCallable)
    void GetMsg(FROSDisparityImg& Output) const;

    virtual void* Get() override;

private:
    virtual FString MsgToString() const override;

    stereo_msgs__msg__DisparityImage disparity_image_msg;
};
