// Copyright 2021 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from geometry_msgs/PoseWithCovarianceStamped.msg - do not modify

#pragma once

#include "CoreMinimal.h"

#include "geometry_msgs/msg/pose_with_covariance_stamped.h"

#include "Msgs/ROS2GenericMsg.h"
#include "rclcUtilities.h"

#include "ROS2PoseWithCovarianceStampedMsg.generated.h"

USTRUCT(Blueprintable)
struct RCLUE_API FROSPoseWithCovarianceStamped
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	int header_stamp_sec;

	unsigned int header_stamp_nanosec;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FString header_frame_id;

	double pose_pose_position_x;

	double pose_pose_position_y;

	double pose_pose_position_z;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FQuat pose_pose_orientation;

	TArray<double> pose_covariance;

	

	void SetFromROS2(geometry_msgs__msg__PoseWithCovarianceStamped rosdata)
	{
    	header_stamp_sec = rosdata.header.stamp.sec;

		header_stamp_nanosec = rosdata.header.stamp.nanosec;

		header_frame_id.AppendChars(rosdata.header.frame_id.data, rosdata.header.frame_id.size);

		pose_pose_position_x = rosdata.pose.pose.position.x;

		pose_pose_position_y = rosdata.pose.pose.position.y;

		pose_pose_position_z = rosdata.pose.pose.position.z;

		pose_pose_orientation.X = rosdata.pose.pose.orientation.x;
		pose_pose_orientation.Y = rosdata.pose.pose.orientation.y;
		pose_pose_orientation.Z = rosdata.pose.pose.orientation.z;
		pose_pose_orientation.W = rosdata.pose.pose.orientation.w;

		for (int i = 0; i < 36; i++)
		{
			pose_covariance[i] = rosdata.pose.covariance[i];
		}

		
	}

	void SetROS2(geometry_msgs__msg__PoseWithCovarianceStamped& rosdata) const
	{
    	rosdata.header.stamp.sec = header_stamp_sec;

		rosdata.header.stamp.nanosec = header_stamp_nanosec;

		if (rosdata.header.frame_id.data != nullptr)
		{
			free(rosdata.header.frame_id.data);
		}
		rosdata.header.frame_id.data = (char*)malloc((header_frame_id.Len()+1)*sizeof(char));
		memcpy(rosdata.header.frame_id.data, TCHAR_TO_ANSI(*header_frame_id), (header_frame_id.Len()+1)*sizeof(char));
		rosdata.header.frame_id.size = header_frame_id.Len();
		rosdata.header.frame_id.capacity = header_frame_id.Len() + 1;

		rosdata.pose.pose.position.x = pose_pose_position_x;

		rosdata.pose.pose.position.y = pose_pose_position_y;

		rosdata.pose.pose.position.z = pose_pose_position_z;

		rosdata.pose.pose.orientation.x = pose_pose_orientation.X;
		rosdata.pose.pose.orientation.y = pose_pose_orientation.Y;
		rosdata.pose.pose.orientation.z = pose_pose_orientation.Z;
		rosdata.pose.pose.orientation.w = pose_pose_orientation.W;

		for (int i = 0; i < 36; i++)
		{
			rosdata.pose.covariance[i] = pose_covariance[i];
		}

		
	}
};

UCLASS()
class RCLUE_API UROS2PoseWithCovarianceStampedMsg : public UROS2GenericMsg
{
	GENERATED_BODY()

public:
	virtual void Init() override;
	virtual void Fini() override;

	virtual const rosidl_message_type_support_t* GetTypeSupport() const override;
	
  	UFUNCTION(BlueprintCallable)
	void SetMsg(const FROSPoseWithCovarianceStamped Input);
	
  	UFUNCTION(BlueprintCallable)
	void GetMsg(FROSPoseWithCovarianceStamped& Output);
	
	virtual void* Get() override;

private:
	virtual FString MsgToString() const override;

	geometry_msgs__msg__PoseWithCovarianceStamped pose_with_covariance_stamped_msg;
};