// Copyright 2021 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from sensor_msgs/JoyFeedbackArray.msg - do not modify

#pragma once

#include "CoreMinimal.h"

#include "sensor_msgs/msg/joy_feedback_array.h"

#include "Msgs/ROS2GenericMsg.h"
#include "rclcUtilities.h"

#include "ROS2JoyFeedbackArrayMsg.generated.h"

USTRUCT(Blueprintable)
struct RCLUE_API FROSJoyFeedbackArray
{
	GENERATED_BODY()

public:
	TArray<uint8> array_type;

	TArray<uint8> array_id;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	TArray<float> array_intensity;

	

	void SetFromROS2(sensor_msgs__msg__JoyFeedbackArray rosdata)
	{
    	for (int i = 0; i < rosdata.array.size; i++)
		{
			array_type[i] = rosdata.array.data[i].type;
		}

		for (int i = 0; i < rosdata.array.size; i++)
		{
			array_id[i] = rosdata.array.data[i].id;
		}

		for (int i = 0; i < rosdata.array.size; i++)
		{
			array_intensity[i] = rosdata.array.data[i].intensity;
		}

		
	}

	void SetROS2(sensor_msgs__msg__JoyFeedbackArray& rosdata) const
	{
    	for (int i = 0; i < array_type.Num(); i++)
		{
			rosdata.array.data[i].type = array_type[i];
		}

		for (int i = 0; i < array_id.Num(); i++)
		{
			rosdata.array.data[i].id = array_id[i];
		}

		for (int i = 0; i < array_intensity.Num(); i++)
		{
			rosdata.array.data[i].intensity = array_intensity[i];
		}

		
	}
};

UCLASS()
class RCLUE_API UROS2JoyFeedbackArrayMsg : public UROS2GenericMsg
{
	GENERATED_BODY()

public:
	virtual void Init() override;
	virtual void Fini() override;

	virtual const rosidl_message_type_support_t* GetTypeSupport() const override;
	
  	UFUNCTION(BlueprintCallable)
	void SetMsg(const FROSJoyFeedbackArray Input);
	
  	UFUNCTION(BlueprintCallable)
	void GetMsg(FROSJoyFeedbackArray& Output);
	
	virtual void* Get() override;

private:
	virtual FString MsgToString() const override;

	sensor_msgs__msg__JoyFeedbackArray joy_feedback_array_msg;
};