// Copyright 2021 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from visualization_msgs/msg/InteractiveMarkerFeedback.msg - do not modify

#pragma once

#include <CoreMinimal.h>

#include "visualization_msgs/msg/interactive_marker_feedback.h"

#include "Msgs/ROS2GenericMsg.h"
#include "rclcUtilities.h"

#include "ROS2InteractiveMarkerFeedbackMsg.generated.h"

USTRUCT(Blueprintable)
struct RCLUE_API FROSInteractiveMarkerFeedback
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	int HeaderStampSec = 0;

	UPROPERTY(EditAnywhere)
	unsigned int HeaderStampNanosec = 0;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FString HeaderFrameId;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FString ClientId;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FString MarkerName;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FString ControlName;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	uint8 EventType = 0;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FVector PosePosition = FVector::ZeroVector;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FQuat PoseOrientation = FQuat::Identity;

	UPROPERTY(EditAnywhere)
	unsigned int MenuEntryId = 0;

	UPROPERTY(EditAnywhere)
	double MousePointX = 0.f;

	UPROPERTY(EditAnywhere)
	double MousePointY = 0.f;

	UPROPERTY(EditAnywhere)
	double MousePointZ = 0.f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	bool bMousePointValid = false;

	

	void SetFromROS2(const visualization_msgs__msg__InteractiveMarkerFeedback& in_ros_data)
	{
    	HeaderStampSec = in_ros_data.header.stamp.sec;

		HeaderStampNanosec = in_ros_data.header.stamp.nanosec;

		HeaderFrameId.AppendChars(in_ros_data.header.frame_id.data, in_ros_data.header.frame_id.size);

		ClientId.AppendChars(in_ros_data.client_id.data, in_ros_data.client_id.size);

		MarkerName.AppendChars(in_ros_data.marker_name.data, in_ros_data.marker_name.size);

		ControlName.AppendChars(in_ros_data.control_name.data, in_ros_data.control_name.size);

		EventType = in_ros_data.event_type;

		PosePosition.X = in_ros_data.pose.position.x;
		PosePosition.Y = in_ros_data.pose.position.y;
		PosePosition.Z = in_ros_data.pose.position.z;

		PoseOrientation.X = in_ros_data.pose.orientation.x;
		PoseOrientation.Y = in_ros_data.pose.orientation.y;
		PoseOrientation.Z = in_ros_data.pose.orientation.z;
		PoseOrientation.W = in_ros_data.pose.orientation.w;

		MenuEntryId = in_ros_data.menu_entry_id;

		MousePointX = in_ros_data.mouse_point.x;

		MousePointY = in_ros_data.mouse_point.y;

		MousePointZ = in_ros_data.mouse_point.z;

		bMousePointValid = in_ros_data.mouse_point_valid;

		
	}

	void SetROS2(visualization_msgs__msg__InteractiveMarkerFeedback& out_ros_data) const
	{
    	out_ros_data.header.stamp.sec = HeaderStampSec;

		out_ros_data.header.stamp.nanosec = HeaderStampNanosec;

		{
			FTCHARToUTF8 strUtf8( *HeaderFrameId );
			int32 strLength = strUtf8.Length();
			if (out_ros_data.header.frame_id.data != nullptr)
		{
			free(out_ros_data.header.frame_id.data);
		}
		out_ros_data.header.frame_id.data = (decltype(out_ros_data.header.frame_id.data))malloc((strLength+1)*sizeof(decltype(*out_ros_data.header.frame_id.data)));
		memcpy(out_ros_data.header.frame_id.data, TCHAR_TO_UTF8(*HeaderFrameId), (strLength+1)*sizeof(char));
			out_ros_data.header.frame_id.size = strLength;
			out_ros_data.header.frame_id.capacity = strLength + 1;
		}

		{
			FTCHARToUTF8 strUtf8( *ClientId );
			int32 strLength = strUtf8.Length();
			if (out_ros_data.client_id.data != nullptr)
		{
			free(out_ros_data.client_id.data);
		}
		out_ros_data.client_id.data = (decltype(out_ros_data.client_id.data))malloc((strLength+1)*sizeof(decltype(*out_ros_data.client_id.data)));
		memcpy(out_ros_data.client_id.data, TCHAR_TO_UTF8(*ClientId), (strLength+1)*sizeof(char));
			out_ros_data.client_id.size = strLength;
			out_ros_data.client_id.capacity = strLength + 1;
		}

		{
			FTCHARToUTF8 strUtf8( *MarkerName );
			int32 strLength = strUtf8.Length();
			if (out_ros_data.marker_name.data != nullptr)
		{
			free(out_ros_data.marker_name.data);
		}
		out_ros_data.marker_name.data = (decltype(out_ros_data.marker_name.data))malloc((strLength+1)*sizeof(decltype(*out_ros_data.marker_name.data)));
		memcpy(out_ros_data.marker_name.data, TCHAR_TO_UTF8(*MarkerName), (strLength+1)*sizeof(char));
			out_ros_data.marker_name.size = strLength;
			out_ros_data.marker_name.capacity = strLength + 1;
		}

		{
			FTCHARToUTF8 strUtf8( *ControlName );
			int32 strLength = strUtf8.Length();
			if (out_ros_data.control_name.data != nullptr)
		{
			free(out_ros_data.control_name.data);
		}
		out_ros_data.control_name.data = (decltype(out_ros_data.control_name.data))malloc((strLength+1)*sizeof(decltype(*out_ros_data.control_name.data)));
		memcpy(out_ros_data.control_name.data, TCHAR_TO_UTF8(*ControlName), (strLength+1)*sizeof(char));
			out_ros_data.control_name.size = strLength;
			out_ros_data.control_name.capacity = strLength + 1;
		}

		out_ros_data.event_type = EventType;

		out_ros_data.pose.position.x = PosePosition.X;
		out_ros_data.pose.position.y = PosePosition.Y;
		out_ros_data.pose.position.z = PosePosition.Z;

		out_ros_data.pose.orientation.x = PoseOrientation.X;
		out_ros_data.pose.orientation.y = PoseOrientation.Y;
		out_ros_data.pose.orientation.z = PoseOrientation.Z;
		out_ros_data.pose.orientation.w = PoseOrientation.W;

		out_ros_data.menu_entry_id = MenuEntryId;

		out_ros_data.mouse_point.x = MousePointX;

		out_ros_data.mouse_point.y = MousePointY;

		out_ros_data.mouse_point.z = MousePointZ;

		out_ros_data.mouse_point_valid = bMousePointValid;

		
	}
};

UCLASS()
class RCLUE_API UROS2InteractiveMarkerFeedbackMsg : public UROS2GenericMsg
{
	GENERATED_BODY()

public:
	virtual void Init() override;
	virtual void Fini() override;

	virtual const rosidl_message_type_support_t* GetTypeSupport() const override;
	
  	UFUNCTION(BlueprintCallable)
	void SetMsg(const FROSInteractiveMarkerFeedback& Input);
	
  	UFUNCTION(BlueprintCallable)
	void GetMsg(FROSInteractiveMarkerFeedback& Output) const;
	
	virtual void* Get() override;

private:
	virtual FString MsgToString() const override;

	visualization_msgs__msg__InteractiveMarkerFeedback interactive_marker_feedback_msg;
};