version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.8"
  apt_packages:
    - graphviz

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: false

python:
  install:
    - requirements: docs/requirements.txt
