// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from simulation_interfaces/srv/GetEntityBounds.srv - do not modify

#include "Srvs/ROS2SIGetEntityBounds.h"

const rosidl_service_type_support_t* UROS2SIGetEntityBoundsSrv::GetTypeSupport() const
{
    return ROSIDL_GET_SRV_TYPE_SUPPORT(simulation_interfaces, srv, GetEntityBounds);
}

void UROS2SIGetEntityBoundsSrv::Init()
{
    simulation_interfaces__srv__GetEntityBounds_Request__init(&GetEntityBounds_req);
    simulation_interfaces__srv__GetEntityBounds_Response__init(&GetEntityBounds_res);
}

void UROS2SIGetEntityBoundsSrv::Fini()
{
    simulation_interfaces__srv__GetEntityBounds_Request__fini(&GetEntityBounds_req);
    simulation_interfaces__srv__GetEntityBounds_Response__fini(&GetEntityBounds_res);
}

void UROS2SIGetEntityBoundsSrv::SetRequest(const FROSSIGetEntityBoundsReq& Request)
{
    Request.SetROS2(GetEntityBounds_req);
}

void UROS2SIGetEntityBoundsSrv::GetRequest(FROSSIGetEntityBoundsReq& Request) const
{
    Request.SetFromROS2(GetEntityBounds_req);
}

void UROS2SIGetEntityBoundsSrv::SetResponse(const FROSSIGetEntityBoundsRes& Response)
{
    Response.SetROS2(GetEntityBounds_res);
}

void UROS2SIGetEntityBoundsSrv::GetResponse(FROSSIGetEntityBoundsRes& Response) const
{
    Response.SetFromROS2(GetEntityBounds_res);
}

void* UROS2SIGetEntityBoundsSrv::GetRequest()
{
    return &GetEntityBounds_req;
}

void* UROS2SIGetEntityBoundsSrv::GetResponse()
{
    return &GetEntityBounds_res;
}

FString UROS2SIGetEntityBoundsSrv::SrvRequestToString() const
{
    /* TODO: Fill here */
    checkNoEntry();
    return FString();
}

FString UROS2SIGetEntityBoundsSrv::SrvResponseToString() const
{
    /* TODO: Fill here */
    checkNoEntry();
    return FString();
}
