// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from
// simulation_interfaces/srv/GetSpawnables.srv - do not modify

#include "Srvs/ROS2SIGetSpawnables.h"

const rosidl_service_type_support_t* UROS2SIGetSpawnablesSrv::GetTypeSupport() const
{
    return ROSIDL_GET_SRV_TYPE_SUPPORT(simulation_interfaces, srv, GetSpawnables);
}

void UROS2SIGetSpawnablesSrv::Init()
{
    simulation_interfaces__srv__GetSpawnables_Request__init(&GetSpawnables_req);
    simulation_interfaces__srv__GetSpawnables_Response__init(&GetSpawnables_res);
}

void UROS2SIGetSpawnablesSrv::Fini()
{
    simulation_interfaces__srv__GetSpawnables_Request__fini(&GetSpawnables_req);
    simulation_interfaces__srv__GetSpawnables_Response__fini(&GetSpawnables_res);
}

void UROS2SIGetSpawnablesSrv::SetRequest(const FROSSIGetSpawnablesReq& Request)
{
    Request.SetROS2(GetSpawnables_req);
}

void UROS2SIGetSpawnablesSrv::GetRequest(FROSSIGetSpawnablesReq& Request) const
{
    Request.SetFromROS2(GetSpawnables_req);
}

void UROS2SIGetSpawnablesSrv::SetResponse(const FROSSIGetSpawnablesRes& Response)
{
    Response.SetROS2(GetSpawnables_res);
}

void UROS2SIGetSpawnablesSrv::GetResponse(FROSSIGetSpawnablesRes& Response) const
{
    Response.SetFromROS2(GetSpawnables_res);
}

void* UROS2SIGetSpawnablesSrv::GetRequest()
{
    return &GetSpawnables_req;
}

void* UROS2SIGetSpawnablesSrv::GetResponse()
{
    return &GetSpawnables_res;
}

FString UROS2SIGetSpawnablesSrv::SrvRequestToString() const
{
    /* TODO: Fill here */
    checkNoEntry();
    return FString();
}

FString UROS2SIGetSpawnablesSrv::SrvResponseToString() const
{
    /* TODO: Fill here */
    checkNoEntry();
    return FString();
}
