// Copyright 2021 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from ue4_interfaces/AddInts.srv - do not modify

#include "Srvs/ROS2AddIntsSrv.h"

const rosidl_service_type_support_t* UROS2AddIntsSrv::GetTypeSupport() const
{
    return ROSIDL_GET_SRV_TYPE_SUPPORT(ue4_interfaces, srv, AddInts);
}

void UROS2AddIntsSrv::Init()
{
    ue4_interfaces__srv__AddInts_Request__init(&AddInts_req);
    ue4_interfaces__srv__AddInts_Response__init(&AddInts_res);
}

void UROS2AddIntsSrv::Fini()
{
    ue4_interfaces__srv__AddInts_Request__fini(&AddInts_req);
    ue4_interfaces__srv__AddInts_Response__fini(&AddInts_res);
}

void UROS2AddIntsSrv::SetRequest(const FROSAddInts_Request& Request)
{
    Request.SetROS2(AddInts_req);
}

void UROS2AddIntsSrv::GetRequest(FROSAddInts_Request& Request) const
{
    Request.SetFromROS2(AddInts_req);
}

void UROS2AddIntsSrv::SetResponse(const FROSAddInts_Response& Response)
{
    Response.SetROS2(AddInts_res);
}

void UROS2AddIntsSrv::GetResponse(FROSAddInts_Response& Response) const
{
    Response.SetFromROS2(AddInts_res);
}

void* UROS2AddIntsSrv::GetRequest()
{
    return &AddInts_req;
}

void* UROS2AddIntsSrv::GetResponse()
{
    return &AddInts_res;
}

FString UROS2AddIntsSrv::SrvRequestToString() const
{
    /* TODO: Fill here */
	checkNoEntry();
    return FString();
}

FString UROS2AddIntsSrv::SrvResponseToString() const
{
    /* TODO: Fill here */
	checkNoEntry();
    return FString();
}