// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from
// simulation_interfaces/srv/UnloadWorld.srv - do not modify

#include "Srvs/ROS2SIUnloadWorld.h"

const rosidl_service_type_support_t* UROS2SIUnloadWorldSrv::GetTypeSupport() const
{
    return ROSIDL_GET_SRV_TYPE_SUPPORT(simulation_interfaces, srv, UnloadWorld);
}

void UROS2SIUnloadWorldSrv::Init()
{
    simulation_interfaces__srv__UnloadWorld_Request__init(&UnloadWorld_req);
    simulation_interfaces__srv__UnloadWorld_Response__init(&UnloadWorld_res);
}

void UROS2SIUnloadWorldSrv::Fini()
{
    simulation_interfaces__srv__UnloadWorld_Request__fini(&UnloadWorld_req);
    simulation_interfaces__srv__UnloadWorld_Response__fini(&UnloadWorld_res);
}

void UROS2SIUnloadWorldSrv::SetRequest(const FROSSIUnloadWorldReq& Request)
{
    Request.SetROS2(UnloadWorld_req);
}

void UROS2SIUnloadWorldSrv::GetRequest(FROSSIUnloadWorldReq& Request) const
{
    Request.SetFromROS2(UnloadWorld_req);
}

void UROS2SIUnloadWorldSrv::SetResponse(const FROSSIUnloadWorldRes& Response)
{
    Response.SetROS2(UnloadWorld_res);
}

void UROS2SIUnloadWorldSrv::GetResponse(FROSSIUnloadWorldRes& Response) const
{
    Response.SetFromROS2(UnloadWorld_res);
}

void* UROS2SIUnloadWorldSrv::GetRequest()
{
    return &UnloadWorld_req;
}

void* UROS2SIUnloadWorldSrv::GetResponse()
{
    return &UnloadWorld_res;
}

FString UROS2SIUnloadWorldSrv::SrvRequestToString() const
{
    /* TODO: Fill here */
    checkNoEntry();
    return FString();
}

FString UROS2SIUnloadWorldSrv::SrvResponseToString() const
{
    /* TODO: Fill here */
    checkNoEntry();
    return FString();
}
