// Copyright 2021 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from ue_msgs/srv/SpawnEntities.srv - do not modify

#include "Srvs/ROS2SpawnEntitiesSrv.h"

const rosidl_service_type_support_t* UROS2SpawnEntitiesSrv::GetTypeSupport() const
{
    return ROSIDL_GET_SRV_TYPE_SUPPORT(ue_msgs, srv, SpawnEntities);
}

void UROS2SpawnEntitiesSrv::Init()
{
    ue_msgs__srv__SpawnEntities_Request__init(&SpawnEntities_req);
    ue_msgs__srv__SpawnEntities_Response__init(&SpawnEntities_res);
}

void UROS2SpawnEntitiesSrv::Fini()
{
    ue_msgs__srv__SpawnEntities_Request__fini(&SpawnEntities_req);
    ue_msgs__srv__SpawnEntities_Response__fini(&SpawnEntities_res);
}

void UROS2SpawnEntitiesSrv::SetRequest(const FROSSpawnEntitiesRequest& Request)
{
    Request.SetROS2(SpawnEntities_req);
}

void UROS2SpawnEntitiesSrv::GetRequest(FROSSpawnEntitiesRequest& Request) const
{
    Request.SetFromROS2(SpawnEntities_req);
}

void UROS2SpawnEntitiesSrv::SetResponse(const FROSSpawnEntitiesResponse& Response)
{
    Response.SetROS2(SpawnEntities_res);
}

void UROS2SpawnEntitiesSrv::GetResponse(FROSSpawnEntitiesResponse& Response) const
{
    Response.SetFromROS2(SpawnEntities_res);
}

void* UROS2SpawnEntitiesSrv::GetRequest()
{
    return &SpawnEntities_req;
}

void* UROS2SpawnEntitiesSrv::GetResponse()
{
    return &SpawnEntities_res;
}

FString UROS2SpawnEntitiesSrv::SrvRequestToString() const
{
    /* TODO: Fill here */
	checkNoEntry();
    return FString();
}

FString UROS2SpawnEntitiesSrv::SrvResponseToString() const
{
    /* TODO: Fill here */
	checkNoEntry();
    return FString();
}