// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from simulation_interfaces/srv/GetCurrentWorld.srv - do not modify

#include "Srvs/ROS2SIGetCurrentWorld.h"

const rosidl_service_type_support_t* UROS2SIGetCurrentWorldSrv::GetTypeSupport() const
{
    return ROSIDL_GET_SRV_TYPE_SUPPORT(simulation_interfaces, srv, GetCurrentWorld);
}

void UROS2SIGetCurrentWorldSrv::Init()
{
    simulation_interfaces__srv__GetCurrentWorld_Request__init(&GetCurrentWorld_req);
    simulation_interfaces__srv__GetCurrentWorld_Response__init(&GetCurrentWorld_res);
}

void UROS2SIGetCurrentWorldSrv::Fini()
{
    simulation_interfaces__srv__GetCurrentWorld_Request__fini(&GetCurrentWorld_req);
    simulation_interfaces__srv__GetCurrentWorld_Response__fini(&GetCurrentWorld_res);
}

void UROS2SIGetCurrentWorldSrv::SetRequest(const FROSSIGetCurrentWorldReq& Request)
{
    Request.SetROS2(GetCurrentWorld_req);
}

void UROS2SIGetCurrentWorldSrv::GetRequest(FROSSIGetCurrentWorldReq& Request) const
{
    Request.SetFromROS2(GetCurrentWorld_req);
}

void UROS2SIGetCurrentWorldSrv::SetResponse(const FROSSIGetCurrentWorldRes& Response)
{
    Response.SetROS2(GetCurrentWorld_res);
}

void UROS2SIGetCurrentWorldSrv::GetResponse(FROSSIGetCurrentWorldRes& Response) const
{
    Response.SetFromROS2(GetCurrentWorld_res);
}

void* UROS2SIGetCurrentWorldSrv::GetRequest()
{
    return &GetCurrentWorld_req;
}

void* UROS2SIGetCurrentWorldSrv::GetResponse()
{
    return &GetCurrentWorld_res;
}

FString UROS2SIGetCurrentWorldSrv::SrvRequestToString() const
{
    /* TODO: Fill here */
    checkNoEntry();
    return FString();
}

FString UROS2SIGetCurrentWorldSrv::SrvResponseToString() const
{
    /* TODO: Fill here */
    checkNoEntry();
    return FString();
}
