// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from example_interfaces/action/Fibonacci.action - do not modify

#include "Actions/ROS2Fibonacci.h"

const rosidl_action_type_support_t* UROS2FibonacciAction::GetTypeSupport() const
{
    return ROSIDL_GET_ACTION_TYPE_SUPPORT(example_interfaces, Fibonacci);
}

void UROS2FibonacciAction::Init()
{
    Super::Init();
    example_interfaces__action__Fibonacci_SendGoal_Request__init(&Fibonacci_goal_request);
    example_interfaces__action__Fibonacci_SendGoal_Response__init(&Fibonacci_goal_response);
    example_interfaces__action__Fibonacci_GetResult_Request__init(&Fibonacci_result_request);
    example_interfaces__action__Fibonacci_GetResult_Response__init(&Fibonacci_result_response);
    example_interfaces__action__Fibonacci_FeedbackMessage__init(&Fibonacci_feedback_message);
}

void UROS2FibonacciAction::Fini()
{
    example_interfaces__action__Fibonacci_SendGoal_Request__fini(&Fibonacci_goal_request);
    example_interfaces__action__Fibonacci_SendGoal_Response__fini(&Fibonacci_goal_response);
    example_interfaces__action__Fibonacci_GetResult_Request__fini(&Fibonacci_result_request);
    example_interfaces__action__Fibonacci_GetResult_Response__fini(&Fibonacci_result_response);
    example_interfaces__action__Fibonacci_FeedbackMessage__fini(&Fibonacci_feedback_message);
    Super::Fini();
}

void UROS2FibonacciAction::SetGoalRequest(const FROSFibonacciSGReq& Goal)
{
    Goal.SetROS2(Fibonacci_goal_request);
}

void UROS2FibonacciAction::GetGoalRequest(FROSFibonacciSGReq& Goal) const
{
    Goal.SetFromROS2(Fibonacci_goal_request);
}

void UROS2FibonacciAction::SetGoalResponse(const FROSFibonacciSGRes& Goal)
{
    Goal.SetROS2(Fibonacci_goal_response);
}

void UROS2FibonacciAction::GetGoalResponse(FROSFibonacciSGRes& Goal) const
{
    Goal.SetFromROS2(Fibonacci_goal_response);
}

void UROS2FibonacciAction::SetResultRequest(const FROSFibonacciGRReq& Result)
{
    Result.SetROS2(Fibonacci_result_request);
}

void UROS2FibonacciAction::GetResultRequest(FROSFibonacciGRReq& Result) const
{
    Result.SetFromROS2(Fibonacci_result_request);
}

void UROS2FibonacciAction::SetResultResponse(const FROSFibonacciGRRes& Result)
{
    Result.SetROS2(Fibonacci_result_response);
}

void UROS2FibonacciAction::GetResultResponse(FROSFibonacciGRRes& Result) const
{
    Result.SetFromROS2(Fibonacci_result_response);
}

void UROS2FibonacciAction::SetFeedback(const FROSFibonacciFB& Feedback)
{
    Feedback.SetROS2(Fibonacci_feedback_message);
}

void UROS2FibonacciAction::GetFeedback(FROSFibonacciFB& Feedback) const
{
    Feedback.SetFromROS2(Fibonacci_feedback_message);
}

void UROS2FibonacciAction::SetGoalIdToFeedback(FROSFibonacciFB& Feedback)
{
    for (int i = 0; i < 16; i++)
    {
        Feedback.GoalId[i] = Fibonacci_goal_request.goal_id.uuid[i];
    }
}

void* UROS2FibonacciAction::GetGoalRequest()
{
    return &Fibonacci_goal_request;
}

void* UROS2FibonacciAction::GetGoalResponse()
{
    return &Fibonacci_goal_response;
}

void* UROS2FibonacciAction::GetResultRequest()
{
    return &Fibonacci_result_request;
}

void* UROS2FibonacciAction::GetResultResponse()
{
    return &Fibonacci_result_response;
}

void* UROS2FibonacciAction::GetFeedbackMessage()
{
    return &Fibonacci_feedback_message;
}
