// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from simulation_interfaces/srv/GetEntities.srv - do not modify

#pragma once

// UE
#include "CoreMinimal.h"

// ROS
#include "simulation_interfaces/srv/get_entities.h"

// rclUE
#include "Srvs/ROS2GenericSrv.h"
#include "rclcUtilities.h"

// Generated Msg/Srv/Action(can be empty)
#include "Msgs/ROS2SIEntityFilters.h"
#include "Msgs/ROS2SIResult.h"
#include "rosidl_runtime_c/string_functions.h"

// Generated
#include "ROS2SIGetEntities.generated.h"

// potential problem: if this struct is defined multiple times!
USTRUCT(Blueprintable)
struct RCLUE_API FROSSIGetEntitiesReq
{
    GENERATED_BODY()

public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    FROSSIEntityFilters Filters;

    FROSSIGetEntitiesReq()
    {
    }

    void SetFromROS2(const simulation_interfaces__srv__GetEntities_Request& in_ros_data)
    {
        Filters.SetFromROS2(in_ros_data.filters);
    }

    void SetROS2(simulation_interfaces__srv__GetEntities_Request& out_ros_data) const
    {
        Filters.SetROS2(out_ros_data.filters);
    }
};

USTRUCT(Blueprintable)
struct RCLUE_API FROSSIGetEntitiesRes
{
    GENERATED_BODY()

public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    FROSSIResult Result;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    TArray<FString> Entities;

    FROSSIGetEntitiesRes()
    {
    }

    void SetFromROS2(const simulation_interfaces__srv__GetEntities_Response& in_ros_data)
    {
        Result.SetFromROS2(in_ros_data.result);

        UROS2Utils::StringSequenceROSToUEArray<rosidl_runtime_c__String>(
            in_ros_data.entities.data, Entities, in_ros_data.entities.size);
    }

    void SetROS2(simulation_interfaces__srv__GetEntities_Response& out_ros_data) const
    {
        Result.SetROS2(out_ros_data.result);

        if (out_ros_data.entities.data)
        {
            rosidl_runtime_c__String__Sequence__fini(&out_ros_data.entities);
        }
        if (!rosidl_runtime_c__String__Sequence__init(&out_ros_data.entities, Entities.Num()))
        {
            UE_LOG_WITH_INFO(LogTemp, Error, TEXT("failed to create array for field out_ros_data.entities  "));
        }
        UROS2Utils::StringArrayUEToROSSequence(Entities, out_ros_data.entities.data, Entities.Num());
    }
};

UCLASS()
class RCLUE_API UROS2SIGetEntitiesSrv : public UROS2GenericSrv
{
    GENERATED_BODY()

public:
    UFUNCTION(BlueprintCallable)
    virtual void Init() override;

    UFUNCTION(BlueprintCallable)
    virtual void Fini() override;

    virtual const rosidl_service_type_support_t* GetTypeSupport() const override;

    // used by client
    UFUNCTION(BlueprintCallable)
    void SetRequest(const FROSSIGetEntitiesReq& Request);

    // used by service
    UFUNCTION(BlueprintCallable)
    void GetRequest(FROSSIGetEntitiesReq& Request) const;

    // used by service
    UFUNCTION(BlueprintCallable)
    void SetResponse(const FROSSIGetEntitiesRes& Response);

    // used by client
    UFUNCTION(BlueprintCallable)
    void GetResponse(FROSSIGetEntitiesRes& Response) const;

    virtual void* GetRequest() override;
    virtual void* GetResponse() override;

private:
    virtual FString SrvRequestToString() const override;
    virtual FString SrvResponseToString() const override;

    simulation_interfaces__srv__GetEntities_Request GetEntities_req;
    simulation_interfaces__srv__GetEntities_Response GetEntities_res;
};
