// Copyright 2021 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from example_interfaces/Trigger.srv - do not modify

#pragma once

#include <CoreMinimal.h>

#include "Srvs/ROS2GenericSrv.h"
#include "rclcUtilities.h"
#include "example_interfaces/srv/trigger.h"

#include "ROS2TriggerSrv.generated.h"

// potential problem: if this struct is defined multiple times!
USTRUCT(Blueprintable)
struct RCLUE_API FROSTrigger_Request
{
	GENERATED_BODY()

public:
	

	void SetFromROS2(const example_interfaces__srv__Trigger_Request& in_ros_data)
	{
    	
	}

	void SetROS2(example_interfaces__srv__Trigger_Request& out_ros_data) const
	{
    	
	}
};

USTRUCT(Blueprintable)
struct RCLUE_API FROSTrigger_Response
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	bool success;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FString message;

	

	void SetFromROS2(const example_interfaces__srv__Trigger_Response& in_ros_data)
	{
    	success = in_ros_data.success;

		message.AppendChars(in_ros_data.message.data, in_ros_data.message.size);

		
	}

	void SetROS2(example_interfaces__srv__Trigger_Response& out_ros_data) const
	{
    	out_ros_data.success = success;

		{
			FTCHARToUTF8 strUtf8( *message );
			int32 strLength = strUtf8.Length();
			if (out_ros_data.message.data != nullptr)
		{
			free(out_ros_data.message.data);
		}
		out_ros_data.message.data = (decltype(out_ros_data.message.data))malloc((strLength+1)*sizeof(decltype(*out_ros_data.message.data)));
		memcpy(out_ros_data.message.data, TCHAR_TO_UTF8(*message), (strLength+1)*sizeof(char));
			out_ros_data.message.size = strLength;
			out_ros_data.message.capacity = strLength + 1;
		}

		
	}
};

UCLASS()
class RCLUE_API UROS2TriggerSrv : public UROS2GenericSrv
{
	GENERATED_BODY()

public:
  	UFUNCTION(BlueprintCallable)
	virtual void Init() override;

  	UFUNCTION(BlueprintCallable)
	virtual void Fini() override;

	virtual const rosidl_service_type_support_t* GetTypeSupport() const override;
	
	// used by client
  	UFUNCTION(BlueprintCallable)
	void SetRequest(const FROSTrigger_Request& Request);
	
	// used by service
  	UFUNCTION(BlueprintCallable)
	void GetRequest(FROSTrigger_Request& Request) const;
	
	// used by service
  	UFUNCTION(BlueprintCallable)
	void SetResponse(const FROSTrigger_Response& Response);
	
	// used by client
  	UFUNCTION(BlueprintCallable)
	void GetResponse(FROSTrigger_Response& Response) const;
	
	virtual void* GetRequest() override;
	virtual void* GetResponse() override;

private:
	virtual FString SrvRequestToString() const override;
	virtual FString SrvResponseToString() const override;

	example_interfaces__srv__Trigger_Request Trigger_req;
	example_interfaces__srv__Trigger_Response Trigger_res;
};