// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from
// simulation_interfaces/srv/GetEntityState.srv - do not modify

#pragma once

// UE
#include "CoreMinimal.h"

// ROS
#include "simulation_interfaces/srv/get_entity_state.h"

// rclUE
#include "Srvs/ROS2GenericSrv.h"
#include "rclcUtilities.h"

// Generated Msg/Srv/Action(can be empty)

#include "Msgs/ROS2SIEntityState.h"
#include "Msgs/ROS2SIResult.h"

// Generated
#include "ROS2SIGetEntityState.generated.h"

// potential problem: if this struct is defined multiple times!
USTRUCT(Blueprintable)
struct RCLUE_API FROSSIGetEntityStateReq
{
    GENERATED_BODY()

public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    FString Entity;

    FROSSIGetEntityStateReq()
    {
    }

    void SetFromROS2(const simulation_interfaces__srv__GetEntityState_Request& in_ros_data)
    {
        Entity = UROS2Utils::StringROSToUE<rosidl_runtime_c__String>(in_ros_data.entity);
    }

    void SetROS2(simulation_interfaces__srv__GetEntityState_Request& out_ros_data) const
    {
        UROS2Utils::StringUEToROS(Entity, out_ros_data.entity);
    }
};

USTRUCT(Blueprintable)
struct RCLUE_API FROSSIGetEntityStateRes
{
    GENERATED_BODY()

public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    FROSSIResult Result;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    FROSSIEntityState State;

    FROSSIGetEntityStateRes()
    {
    }

    void SetFromROS2(const simulation_interfaces__srv__GetEntityState_Response& in_ros_data)
    {
        Result.SetFromROS2(in_ros_data.result);

        State.SetFromROS2(in_ros_data.state);
    }

    void SetROS2(simulation_interfaces__srv__GetEntityState_Response& out_ros_data) const
    {
        Result.SetROS2(out_ros_data.result);

        State.SetROS2(out_ros_data.state);
    }
};

UCLASS()
class RCLUE_API UROS2SIGetEntityStateSrv : public UROS2GenericSrv
{
    GENERATED_BODY()

public:
    UFUNCTION(BlueprintCallable)
    virtual void Init() override;

    UFUNCTION(BlueprintCallable)
    virtual void Fini() override;

    virtual const rosidl_service_type_support_t* GetTypeSupport() const override;

    // used by client
    UFUNCTION(BlueprintCallable)
    void SetRequest(const FROSSIGetEntityStateReq& Request);

    // used by service
    UFUNCTION(BlueprintCallable)
    void GetRequest(FROSSIGetEntityStateReq& Request) const;

    // used by service
    UFUNCTION(BlueprintCallable)
    void SetResponse(const FROSSIGetEntityStateRes& Response);

    // used by client
    UFUNCTION(BlueprintCallable)
    void GetResponse(FROSSIGetEntityStateRes& Response) const;

    virtual void* GetRequest() override;
    virtual void* GetResponse() override;

private:
    virtual FString SrvRequestToString() const override;
    virtual FString SrvResponseToString() const override;

    simulation_interfaces__srv__GetEntityState_Request GetEntityState_req;
    simulation_interfaces__srv__GetEntityState_Response GetEntityState_res;
};
