// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from
// simulation_interfaces/srv/GetAvailableWorlds.srv - do not modify

#pragma once

// UE
#include "CoreMinimal.h"

// ROS
#include "simulation_interfaces/srv/get_available_worlds.h"

// rclUE
#include "Srvs/ROS2GenericSrv.h"
#include "rclcUtilities.h"

// Generated Msg/Srv/Action(can be empty)
#include "Msgs/ROS2SIResult.h"
#include "Msgs/ROS2SITagsFilter.h"
#include "Msgs/ROS2SIWorldResource.h"
#include "rosidl_runtime_c/string_functions.h"
#include "simulation_interfaces/msg/detail/world_resource__functions.h"

// Generated
#include "ROS2SIGetAvailableWorlds.generated.h"

// potential problem: if this struct is defined multiple times!
USTRUCT(Blueprintable)
struct RCLUE_API FROSSIGetAvailableWorldsReq
{
    GENERATED_BODY()

public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    TArray<FString> AdditionalSources;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    FROSSITagsFilter Filter;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    bool bOfflineOnly = false;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    bool bContinueOnError = false;

    FROSSIGetAvailableWorldsReq()
    {
    }

    void SetFromROS2(const simulation_interfaces__srv__GetAvailableWorlds_Request& in_ros_data)
    {
        UROS2Utils::StringSequenceROSToUEArray<rosidl_runtime_c__String>(
            in_ros_data.additional_sources.data, AdditionalSources, in_ros_data.additional_sources.size);

        Filter.SetFromROS2(in_ros_data.filter);

        bOfflineOnly = in_ros_data.offline_only;

        bContinueOnError = in_ros_data.continue_on_error;
    }

    void SetROS2(simulation_interfaces__srv__GetAvailableWorlds_Request& out_ros_data) const
    {
        if (out_ros_data.additional_sources.data)
        {
            rosidl_runtime_c__String__Sequence__fini(&out_ros_data.additional_sources);
        }
        if (!rosidl_runtime_c__String__Sequence__init(&out_ros_data.additional_sources, AdditionalSources.Num()))
        {
            UE_LOG_WITH_INFO(LogTemp,
                             Error,
                             TEXT("failed to create array for field "
                                  "out_ros_data.additional_sources  "));
        }
        UROS2Utils::StringArrayUEToROSSequence(AdditionalSources, out_ros_data.additional_sources.data, AdditionalSources.Num());

        Filter.SetROS2(out_ros_data.filter);

        out_ros_data.offline_only = bOfflineOnly;

        out_ros_data.continue_on_error = bContinueOnError;
    }
};

USTRUCT(Blueprintable)
struct RCLUE_API FROSSIGetAvailableWorldsRes
{
    GENERATED_BODY()

public:
    static constexpr uint8 DEFAULT_SOURCES_FAILED = 101;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    FROSSIResult Result;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    TArray<FROSSIWorldResource> Worlds;

    FROSSIGetAvailableWorldsRes()
    {
    }

    void SetFromROS2(const simulation_interfaces__srv__GetAvailableWorlds_Response& in_ros_data)
    {
        Result.SetFromROS2(in_ros_data.result);

        UROS2Utils::SequenceROSToUEArray<simulation_interfaces__msg__WorldResource, FROSSIWorldResource>(
            in_ros_data.worlds.data, Worlds, in_ros_data.worlds.size);
    }

    void SetROS2(simulation_interfaces__srv__GetAvailableWorlds_Response& out_ros_data) const
    {
        Result.SetROS2(out_ros_data.result);

        if (out_ros_data.worlds.data)
        {
            simulation_interfaces__msg__WorldResource__Sequence__fini(&out_ros_data.worlds);
        }
        if (!simulation_interfaces__msg__WorldResource__Sequence__init(&out_ros_data.worlds, Worlds.Num()))
        {
            UE_LOG_WITH_INFO(LogTemp, Error, TEXT("failed to create array for field out_ros_data.worlds  "));
        }
        UROS2Utils::ArrayUEToROSSequence<simulation_interfaces__msg__WorldResource, FROSSIWorldResource>(
            Worlds, out_ros_data.worlds.data, Worlds.Num());
    }
};

UCLASS()
class RCLUE_API UROS2SIGetAvailableWorldsSrv : public UROS2GenericSrv
{
    GENERATED_BODY()

public:
    UFUNCTION(BlueprintCallable)
    virtual void Init() override;

    UFUNCTION(BlueprintCallable)
    virtual void Fini() override;

    virtual const rosidl_service_type_support_t* GetTypeSupport() const override;

    // used by client
    UFUNCTION(BlueprintCallable)
    void SetRequest(const FROSSIGetAvailableWorldsReq& Request);

    // used by service
    UFUNCTION(BlueprintCallable)
    void GetRequest(FROSSIGetAvailableWorldsReq& Request) const;

    // used by service
    UFUNCTION(BlueprintCallable)
    void SetResponse(const FROSSIGetAvailableWorldsRes& Response);

    // used by client
    UFUNCTION(BlueprintCallable)
    void GetResponse(FROSSIGetAvailableWorldsRes& Response) const;

    virtual void* GetRequest() override;
    virtual void* GetResponse() override;

    UFUNCTION(BlueprintCallable)
    static uint8 CONST_DEFAULT_SOURCES_FAILED()
    {
        return FROSSIGetAvailableWorldsRes::DEFAULT_SOURCES_FAILED;
    }

private:
    virtual FString SrvRequestToString() const override;
    virtual FString SrvResponseToString() const override;

    simulation_interfaces__srv__GetAvailableWorlds_Request GetAvailableWorlds_req;
    simulation_interfaces__srv__GetAvailableWorlds_Response GetAvailableWorlds_res;
};
