// Copyright 2021 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from ue_msgs/srv/SpawnWorld.srv - do not
// modify

#pragma once

// UE
#include <CoreMinimal.h>

// ROS
#include "ue_msgs/srv/spawn_world.h"

// rclUE
#include "Srvs/ROS2GenericSrv.h"
#include "rclcUtilities.h"

// Generated Msg/Srv/Action(can be empty)
#include "Msgs/ROS2Pose.h"

// Generated
#include "ROS2SpawnWorld.generated.h"

// potential problem: if this struct is defined multiple times!
USTRUCT(Blueprintable)
struct RCLUE_API FROSSpawnWorldReq {
  GENERATED_BODY()

public:
  UPROPERTY(EditAnywhere, BlueprintReadWrite)
  FString WorldModel;

  UPROPERTY(EditAnywhere, BlueprintReadWrite)
  FString WorldInstanceName;

  UPROPERTY(EditAnywhere, BlueprintReadWrite)
  FROSPose Pose;

  FROSSpawnWorldReq() {}

  void SetFromROS2(const ue_msgs__srv__SpawnWorld_Request &in_ros_data) {
    WorldModel.AppendChars(in_ros_data.world_model.data,
                           in_ros_data.world_model.size);

    WorldInstanceName.AppendChars(in_ros_data.world_instance_name.data,
                                  in_ros_data.world_instance_name.size);

    Pose.SetFromROS2(in_ros_data.pose);
  }

  void SetROS2(ue_msgs__srv__SpawnWorld_Request &out_ros_data) const {
    {
      FTCHARToUTF8 strUtf8(*WorldModel);
      int32 strLength = strUtf8.Length();
      out_ros_data.world_model.data =
          (decltype(out_ros_data.world_model.data))malloc(
              (strLength + 1) *
              sizeof(decltype(*out_ros_data.world_model.data)));
      memcpy(out_ros_data.world_model.data, TCHAR_TO_UTF8(*WorldModel),
             (strLength + 1) * sizeof(char));
      out_ros_data.world_model.size = strLength;
      out_ros_data.world_model.capacity = strLength + 1;
    }

    {
      FTCHARToUTF8 strUtf8(*WorldInstanceName);
      int32 strLength = strUtf8.Length();
      out_ros_data.world_instance_name.data =
          (decltype(out_ros_data.world_instance_name.data))malloc(
              (strLength + 1) *
              sizeof(decltype(*out_ros_data.world_instance_name.data)));
      memcpy(out_ros_data.world_instance_name.data,
             TCHAR_TO_UTF8(*WorldInstanceName), (strLength + 1) * sizeof(char));
      out_ros_data.world_instance_name.size = strLength;
      out_ros_data.world_instance_name.capacity = strLength + 1;
    }

    Pose.SetROS2(out_ros_data.pose);
  }
};

USTRUCT(Blueprintable)
struct RCLUE_API FROSSpawnWorldRes {
  GENERATED_BODY()

public:
  UPROPERTY(EditAnywhere, BlueprintReadWrite)
  bool bSuccess = false;

  UPROPERTY(EditAnywhere, BlueprintReadWrite)
  FString StatusMessage;

  FROSSpawnWorldRes() {}

  void SetFromROS2(const ue_msgs__srv__SpawnWorld_Response &in_ros_data) {
    bSuccess = in_ros_data.success;

    StatusMessage.AppendChars(in_ros_data.status_message.data,
                              in_ros_data.status_message.size);
  }

  void SetROS2(ue_msgs__srv__SpawnWorld_Response &out_ros_data) const {
    out_ros_data.success = bSuccess;

    {
      FTCHARToUTF8 strUtf8(*StatusMessage);
      int32 strLength = strUtf8.Length();
      out_ros_data.status_message.data =
          (decltype(out_ros_data.status_message.data))malloc(
              (strLength + 1) *
              sizeof(decltype(*out_ros_data.status_message.data)));
      memcpy(out_ros_data.status_message.data, TCHAR_TO_UTF8(*StatusMessage),
             (strLength + 1) * sizeof(char));
      out_ros_data.status_message.size = strLength;
      out_ros_data.status_message.capacity = strLength + 1;
    }
  }
};

UCLASS()
class RCLUE_API UROS2SpawnWorldSrv : public UROS2GenericSrv {
  GENERATED_BODY()

public:
  UFUNCTION(BlueprintCallable)
  virtual void Init() override;

  UFUNCTION(BlueprintCallable)
  virtual void Fini() override;

  virtual const rosidl_service_type_support_t *GetTypeSupport() const override;

  // used by client
  UFUNCTION(BlueprintCallable)
  void SetRequest(const FROSSpawnWorldReq &Request);

  // used by service
  UFUNCTION(BlueprintCallable)
  void GetRequest(FROSSpawnWorldReq &Request) const;

  // used by service
  UFUNCTION(BlueprintCallable)
  void SetResponse(const FROSSpawnWorldRes &Response);

  // used by client
  UFUNCTION(BlueprintCallable)
  void GetResponse(FROSSpawnWorldRes &Response) const;

  virtual void *GetRequest() override;
  virtual void *GetResponse() override;

private:
  virtual FString SrvRequestToString() const override;
  virtual FString SrvResponseToString() const override;

  ue_msgs__srv__SpawnWorld_Request SpawnWorld_req;
  ue_msgs__srv__SpawnWorld_Response SpawnWorld_res;
};