// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from tf2_msgs/msg/TFMessage.msg - do not modify

#include "Msgs/ROS2TFMsg.h"

#include "Kismet/GameplayStatics.h"

void UROS2TFMsgMsg::Init()
{
    tf2_msgs__msg__TFMessage__init(&tf_message_msg);
}

void UROS2TFMsgMsg::Fini()
{
    tf2_msgs__msg__TFMessage__fini(&tf_message_msg);
}

const rosidl_message_type_support_t* UROS2TFMsgMsg::GetTypeSupport() const
{
    return ROSIDL_GET_MSG_TYPE_SUPPORT(tf2_msgs, msg, TFMessage);
}

void UROS2TFMsgMsg::SetMsg(const FROSTFMsg& Inputs)
{
    Inputs.SetROS2(tf_message_msg);
}

void UROS2TFMsgMsg::GetMsg(FROSTFMsg& Outputs) const
{
    Outputs.SetFromROS2(tf_message_msg);
}

void* UROS2TFMsgMsg::Get()
{
    return &tf_message_msg;
}

FString UROS2TFMsgMsg::MsgToString() const
{
    /* TODO: Fill here */
    checkNoEntry();
    return FString();
}
