// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from actionlib_msgs/msg/GoalStatus.msg - do not modify

#include "Msgs/ROS2GoalStatus.h"

#include "Kismet/GameplayStatics.h"

void UROS2GoalStatusMsg::Init()
{
    actionlib_msgs__msg__GoalStatus__init(&goal_status_msg);
}

void UROS2GoalStatusMsg::Fini()
{
    actionlib_msgs__msg__GoalStatus__fini(&goal_status_msg);
}

const rosidl_message_type_support_t* UROS2GoalStatusMsg::GetTypeSupport() const
{
    return ROSIDL_GET_MSG_TYPE_SUPPORT(actionlib_msgs, msg, GoalStatus);
}

void UROS2GoalStatusMsg::SetMsg(const FROSGoalStatus& Inputs)
{
    Inputs.SetROS2(goal_status_msg);
}

void UROS2GoalStatusMsg::GetMsg(FROSGoalStatus& Outputs) const
{
    Outputs.SetFromROS2(goal_status_msg);
}

void* UROS2GoalStatusMsg::Get()
{
    return &goal_status_msg;
}

FString UROS2GoalStatusMsg::MsgToString() const
{
    /* TODO: Fill here */
    checkNoEntry();
    return FString();
}
