// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from simulation_interfaces/msg/TagsFilter.msg - do not modify

#include "Msgs/ROS2SITagsFilter.h"

#include "Kismet/GameplayStatics.h"

void UROS2SITagsFilterMsg::Init()
{
    simulation_interfaces__msg__TagsFilter__init(&tags_filter_msg);
}

void UROS2SITagsFilterMsg::Fini()
{
    simulation_interfaces__msg__TagsFilter__fini(&tags_filter_msg);
}

const rosidl_message_type_support_t* UROS2SITagsFilterMsg::GetTypeSupport() const
{
    return ROSIDL_GET_MSG_TYPE_SUPPORT(simulation_interfaces, msg, TagsFilter);
}

void UROS2SITagsFilterMsg::SetMsg(const FROSSITagsFilter& Inputs)
{
    Inputs.SetROS2(tags_filter_msg);
}

void UROS2SITagsFilterMsg::GetMsg(FROSSITagsFilter& Outputs) const
{
    Outputs.SetFromROS2(tags_filter_msg);
}

void* UROS2SITagsFilterMsg::Get()
{
    return &tags_filter_msg;
}

FString UROS2SITagsFilterMsg::MsgToString() const
{
    /* TODO: Fill here */
    checkNoEntry();
    return FString();
}
