// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from sensor_msgs/msg/LaserScan.msg - do not modify

#include "Msgs/ROS2LaserScan.h"

#include "Kismet/GameplayStatics.h"

void UROS2LaserScanMsg::Init()
{
    sensor_msgs__msg__LaserScan__init(&laser_scan_msg);
}

void UROS2LaserScanMsg::Fini()
{
    sensor_msgs__msg__LaserScan__fini(&laser_scan_msg);
}

const rosidl_message_type_support_t* UROS2LaserScanMsg::GetTypeSupport() const
{
    return ROSIDL_GET_MSG_TYPE_SUPPORT(sensor_msgs, msg, LaserScan);
}

void UROS2LaserScanMsg::SetMsg(const FROSLaserScan& Inputs)
{
    Inputs.SetROS2(laser_scan_msg);
}

void UROS2LaserScanMsg::GetMsg(FROSLaserScan& Outputs) const
{
    Outputs.SetFromROS2(laser_scan_msg);
}

void* UROS2LaserScanMsg::Get()
{
    return &laser_scan_msg;
}

FString UROS2LaserScanMsg::MsgToString() const
{
    /* TODO: Fill here */
    checkNoEntry();
    return FString();
}
