// Copyright 2021 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from UE_msgs/SpawnEntityState.msg - do not modify

#include "Msgs/ROS2SpawnEntityStateMsg.h"

#include "Kismet/GameplayStatics.h"

void UROS2SpawnEntityStateMsg::Init()
{
	ue_msgs__msg__SpawnEntityState__init(&spawn_entity_state_msg);
}

void UROS2SpawnEntityStateMsg::Fini()
{
	ue_msgs__msg__SpawnEntityState__fini(&spawn_entity_state_msg);
}

const rosidl_message_type_support_t* UROS2SpawnEntityStateMsg::GetTypeSupport() const
{
	return ROSIDL_GET_MSG_TYPE_SUPPORT(ue_msgs, msg, SpawnEntityState);
}

void UROS2SpawnEntityStateMsg::SetMsg(const FROSSpawnEntityState& Inputs)
{
    Inputs.SetROS2(spawn_entity_state_msg);
}

void UROS2SpawnEntityStateMsg::GetMsg(FROSSpawnEntityState& Outputs) const
{
    Outputs.SetFromROS2(spawn_entity_state_msg);
}

void* UROS2SpawnEntityStateMsg::Get()
{
	return &spawn_entity_state_msg;
}

FString UROS2SpawnEntityStateMsg::MsgToString() const
{
    /* TODO: Fill here */
	checkNoEntry();
	return FString();
}