// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from std_msgs/msg/ColorRGBA.msg - do not modify

#include "Msgs/ROS2ColorRGBA.h"

#include "Kismet/GameplayStatics.h"

void UROS2ColorRGBAMsg::Init()
{
    std_msgs__msg__ColorRGBA__init(&color_rgba_msg);
}

void UROS2ColorRGBAMsg::Fini()
{
    std_msgs__msg__ColorRGBA__fini(&color_rgba_msg);
}

const rosidl_message_type_support_t* UROS2ColorRGBAMsg::GetTypeSupport() const
{
    return ROSIDL_GET_MSG_TYPE_SUPPORT(std_msgs, msg, ColorRGBA);
}

void UROS2ColorRGBAMsg::SetMsg(const FROSColorRGBA& Inputs)
{
    Inputs.SetROS2(color_rgba_msg);
}

void UROS2ColorRGBAMsg::GetMsg(FROSColorRGBA& Outputs) const
{
    Outputs.SetFromROS2(color_rgba_msg);
}

void* UROS2ColorRGBAMsg::Get()
{
    return &color_rgba_msg;
}

FString UROS2ColorRGBAMsg::MsgToString() const
{
    /* TODO: Fill here */
    checkNoEntry();
    return FString();
}
