// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from simulation_interfaces/msg/EntityInfo.msg - do not modify

#include "Msgs/ROS2SIEntityInfo.h"

#include "Kismet/GameplayStatics.h"

void UROS2SIEntityInfoMsg::Init()
{
    simulation_interfaces__msg__EntityInfo__init(&entity_info_msg);
}

void UROS2SIEntityInfoMsg::Fini()
{
    simulation_interfaces__msg__EntityInfo__fini(&entity_info_msg);
}

const rosidl_message_type_support_t* UROS2SIEntityInfoMsg::GetTypeSupport() const
{
    return ROSIDL_GET_MSG_TYPE_SUPPORT(simulation_interfaces, msg, EntityInfo);
}

void UROS2SIEntityInfoMsg::SetMsg(const FROSSIEntityInfo& Inputs)
{
    Inputs.SetROS2(entity_info_msg);
}

void UROS2SIEntityInfoMsg::GetMsg(FROSSIEntityInfo& Outputs) const
{
    Outputs.SetFromROS2(entity_info_msg);
}

void* UROS2SIEntityInfoMsg::Get()
{
    return &entity_info_msg;
}

FString UROS2SIEntityInfoMsg::MsgToString() const
{
    /* TODO: Fill here */
    checkNoEntry();
    return FString();
}
