// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from visualization_msgs/msg/ImageMarker.msg - do not modify

#include "Msgs/ROS2ImgMarker.h"

#include "Kismet/GameplayStatics.h"

void UROS2ImgMarkerMsg::Init()
{
    visualization_msgs__msg__ImageMarker__init(&image_marker_msg);
}

void UROS2ImgMarkerMsg::Fini()
{
    visualization_msgs__msg__ImageMarker__fini(&image_marker_msg);
}

const rosidl_message_type_support_t* UROS2ImgMarkerMsg::GetTypeSupport() const
{
    return ROSIDL_GET_MSG_TYPE_SUPPORT(visualization_msgs, msg, ImageMarker);
}

void UROS2ImgMarkerMsg::SetMsg(const FROSImgMarker& Inputs)
{
    Inputs.SetROS2(image_marker_msg);
}

void UROS2ImgMarkerMsg::GetMsg(FROSImgMarker& Outputs) const
{
    Outputs.SetFromROS2(image_marker_msg);
}

void* UROS2ImgMarkerMsg::Get()
{
    return &image_marker_msg;
}

FString UROS2ImgMarkerMsg::MsgToString() const
{
    /* TODO: Fill here */
    checkNoEntry();
    return FString();
}
