// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from visualization_msgs/msg/MeshFile.msg - do not modify

#include "Msgs/ROS2MeshFile.h"

#include "Kismet/GameplayStatics.h"

void UROS2MeshFileMsg::Init()
{
    visualization_msgs__msg__MeshFile__init(&mesh_file_msg);
}

void UROS2MeshFileMsg::Fini()
{
    visualization_msgs__msg__MeshFile__fini(&mesh_file_msg);
}

const rosidl_message_type_support_t* UROS2MeshFileMsg::GetTypeSupport() const
{
    return ROSIDL_GET_MSG_TYPE_SUPPORT(visualization_msgs, msg, MeshFile);
}

void UROS2MeshFileMsg::SetMsg(const FROSMeshFile& Inputs)
{
    Inputs.SetROS2(mesh_file_msg);
}

void UROS2MeshFileMsg::GetMsg(FROSMeshFile& Outputs) const
{
    Outputs.SetFromROS2(mesh_file_msg);
}

void* UROS2MeshFileMsg::Get()
{
    return &mesh_file_msg;
}

FString UROS2MeshFileMsg::MsgToString() const
{
    /* TODO: Fill here */
    checkNoEntry();
    return FString();
}
