// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from simulation_interfaces/msg/NamedPose.msg
// - do not modify

#include "Msgs/ROS2SINamedPose.h"

#include "Kismet/GameplayStatics.h"

void UROS2SINamedPoseMsg::Init()
{
    simulation_interfaces__msg__NamedPose__init(&named_pose_msg);
}

void UROS2SINamedPoseMsg::Fini()
{
    simulation_interfaces__msg__NamedPose__fini(&named_pose_msg);
}

const rosidl_message_type_support_t* UROS2SINamedPoseMsg::GetTypeSupport() const
{
    return ROSIDL_GET_MSG_TYPE_SUPPORT(simulation_interfaces, msg, NamedPose);
}

void UROS2SINamedPoseMsg::SetMsg(const FROSSINamedPose& Inputs)
{
    Inputs.SetROS2(named_pose_msg);
}

void UROS2SINamedPoseMsg::GetMsg(FROSSINamedPose& Outputs) const
{
    Outputs.SetFromROS2(named_pose_msg);
}

void* UROS2SINamedPoseMsg::Get()
{
    return &named_pose_msg;
}

FString UROS2SINamedPoseMsg::MsgToString() const
{
    /* TODO: Fill here */
    checkNoEntry();
    return FString();
}
