// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from geometry_msgs/msg/Wrench.msg - do not modify

#include "Msgs/ROS2Wrench.h"

#include "Kismet/GameplayStatics.h"

void UROS2WrenchMsg::Init()
{
    geometry_msgs__msg__Wrench__init(&wrench_msg);
}

void UROS2WrenchMsg::Fini()
{
    geometry_msgs__msg__Wrench__fini(&wrench_msg);
}

const rosidl_message_type_support_t* UROS2WrenchMsg::GetTypeSupport() const
{
    return ROSIDL_GET_MSG_TYPE_SUPPORT(geometry_msgs, msg, Wrench);
}

void UROS2WrenchMsg::SetMsg(const FROSWrench& Inputs)
{
    Inputs.SetROS2(wrench_msg);
}

void UROS2WrenchMsg::GetMsg(FROSWrench& Outputs) const
{
    Outputs.SetFromROS2(wrench_msg);
}

void* UROS2WrenchMsg::Get()
{
    return &wrench_msg;
}

FString UROS2WrenchMsg::MsgToString() const
{
    /* TODO: Fill here */
    checkNoEntry();
    return FString();
}
