// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from sensor_msgs/msg/CameraInfo.msg - do not modify

#include "Msgs/ROS2CameraInfo.h"

#include "Kismet/GameplayStatics.h"

void UROS2CameraInfoMsg::Init()
{
    sensor_msgs__msg__CameraInfo__init(&camera_info_msg);
}

void UROS2CameraInfoMsg::Fini()
{
    sensor_msgs__msg__CameraInfo__fini(&camera_info_msg);
}

const rosidl_message_type_support_t* UROS2CameraInfoMsg::GetTypeSupport() const
{
    return ROSIDL_GET_MSG_TYPE_SUPPORT(sensor_msgs, msg, CameraInfo);
}

void UROS2CameraInfoMsg::SetMsg(const FROSCameraInfo& Inputs)
{
    Inputs.SetROS2(camera_info_msg);
}

void UROS2CameraInfoMsg::GetMsg(FROSCameraInfo& Outputs) const
{
    Outputs.SetFromROS2(camera_info_msg);
}

void* UROS2CameraInfoMsg::Get()
{
    return &camera_info_msg;
}

FString UROS2CameraInfoMsg::MsgToString() const
{
    /* TODO: Fill here */
    checkNoEntry();
    return FString();
}
