// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from ue_msgs/msg/IntPointDict.msg - do not modify

#include "Msgs/ROS2IntPointDict.h"

#include "Kismet/GameplayStatics.h"

void UROS2IntPointDictMsg::Init()
{
    ue_msgs__msg__IntPointDict__init(&int_point_dict_msg);
}

void UROS2IntPointDictMsg::Fini()
{
    ue_msgs__msg__IntPointDict__fini(&int_point_dict_msg);
}

const rosidl_message_type_support_t* UROS2IntPointDictMsg::GetTypeSupport() const
{
    return ROSIDL_GET_MSG_TYPE_SUPPORT(ue_msgs, msg, IntPointDict);
}

void UROS2IntPointDictMsg::SetMsg(const FROSIntPointDict& Inputs)
{
    Inputs.SetROS2(int_point_dict_msg);
}

void UROS2IntPointDictMsg::GetMsg(FROSIntPointDict& Outputs) const
{
    Outputs.SetFromROS2(int_point_dict_msg);
}

void* UROS2IntPointDictMsg::Get()
{
    return &int_point_dict_msg;
}

FString UROS2IntPointDictMsg::MsgToString() const
{
    /* TODO: Fill here */
    checkNoEntry();
    return FString();
}
