// Copyright 2023 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from ue_msgs/msg/OverlappingObjects.msg - do not modify

#include "Msgs/ROS2OverlappingObjects.h"

#include "Kismet/GameplayStatics.h"

void UROS2OverlappingObjectsMsg::Init()
{
    ue_msgs__msg__OverlappingObjects__init(&overlapping_objects_msg);
}

void UROS2OverlappingObjectsMsg::Fini()
{
    ue_msgs__msg__OverlappingObjects__fini(&overlapping_objects_msg);
}

const rosidl_message_type_support_t* UROS2OverlappingObjectsMsg::GetTypeSupport() const
{
    return ROSIDL_GET_MSG_TYPE_SUPPORT(ue_msgs, msg, OverlappingObjects);
}

void UROS2OverlappingObjectsMsg::SetMsg(const FROSOverlappingObjects& Inputs)
{
    Inputs.SetROS2(overlapping_objects_msg);
}

void UROS2OverlappingObjectsMsg::GetMsg(FROSOverlappingObjects& Outputs) const
{
    Outputs.SetFromROS2(overlapping_objects_msg);
}

void* UROS2OverlappingObjectsMsg::Get()
{
    return &overlapping_objects_msg;
}

FString UROS2OverlappingObjectsMsg::MsgToString() const
{
    /* TODO: Fill here */
    checkNoEntry();
    return FString();
}
