// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from visualization_msgs/msg/MarkerArray.msg - do not modify

#include "Msgs/ROS2MarkerArray.h"

#include "Kismet/GameplayStatics.h"

void UROS2MarkerArrayMsg::Init()
{
    visualization_msgs__msg__MarkerArray__init(&marker_array_msg);
}

void UROS2MarkerArrayMsg::Fini()
{
    visualization_msgs__msg__MarkerArray__fini(&marker_array_msg);
}

const rosidl_message_type_support_t* UROS2MarkerArrayMsg::GetTypeSupport() const
{
    return ROSIDL_GET_MSG_TYPE_SUPPORT(visualization_msgs, msg, MarkerArray);
}

void UROS2MarkerArrayMsg::SetMsg(const FROSMarkerArray& Inputs)
{
    Inputs.SetROS2(marker_array_msg);
}

void UROS2MarkerArrayMsg::GetMsg(FROSMarkerArray& Outputs) const
{
    Outputs.SetFromROS2(marker_array_msg);
}

void* UROS2MarkerArrayMsg::Get()
{
    return &marker_array_msg;
}

FString UROS2MarkerArrayMsg::MsgToString() const
{
    /* TODO: Fill here */
    checkNoEntry();
    return FString();
}
