// Copyright 2021 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from geometry_msgs/TwistWithCovarianceStamped.msg - do not modify

#include "Msgs/ROS2TwistWithCovarianceStampedMsg.h"

#include "Kismet/GameplayStatics.h"

void UROS2TwistWithCovarianceStampedMsg::Init()
{
	geometry_msgs__msg__TwistWithCovarianceStamped__init(&twist_with_covariance_stamped_msg);
}

void UROS2TwistWithCovarianceStampedMsg::Fini()
{
	geometry_msgs__msg__TwistWithCovarianceStamped__fini(&twist_with_covariance_stamped_msg);
}

const rosidl_message_type_support_t* UROS2TwistWithCovarianceStampedMsg::GetTypeSupport() const
{
	return ROSIDL_GET_MSG_TYPE_SUPPORT(geometry_msgs, msg, TwistWithCovarianceStamped);
}

void UROS2TwistWithCovarianceStampedMsg::SetMsg(const FROSTwistWithCovarianceStamped Inputs)
{
    Inputs.SetROS2(twist_with_covariance_stamped_msg);
}

void UROS2TwistWithCovarianceStampedMsg::GetMsg(FROSTwistWithCovarianceStamped& Outputs)
{
    Outputs.SetFromROS2(twist_with_covariance_stamped_msg);
}

void* UROS2TwistWithCovarianceStampedMsg::Get()
{
	return &twist_with_covariance_stamped_msg;
}

FString UROS2TwistWithCovarianceStampedMsg::MsgToString() const
{
    /* TODO: Fill here */
	checkNoEntry();
	return FString();
}