// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from simulation_interfaces/msg/SimulatorFeatures.msg - do not modify

#include "Msgs/ROS2SISimulatorFeatures.h"

#include "Kismet/GameplayStatics.h"

void UROS2SISimulatorFeaturesMsg::Init()
{
    simulation_interfaces__msg__SimulatorFeatures__init(&simulator_features_msg);
}

void UROS2SISimulatorFeaturesMsg::Fini()
{
    simulation_interfaces__msg__SimulatorFeatures__fini(&simulator_features_msg);
}

const rosidl_message_type_support_t* UROS2SISimulatorFeaturesMsg::GetTypeSupport() const
{
    return ROSIDL_GET_MSG_TYPE_SUPPORT(simulation_interfaces, msg, SimulatorFeatures);
}

void UROS2SISimulatorFeaturesMsg::SetMsg(const FROSSISimulatorFeatures& Inputs)
{
    Inputs.SetROS2(simulator_features_msg);
}

void UROS2SISimulatorFeaturesMsg::GetMsg(FROSSISimulatorFeatures& Outputs) const
{
    Outputs.SetFromROS2(simulator_features_msg);
}

void* UROS2SISimulatorFeaturesMsg::Get()
{
    return &simulator_features_msg;
}

FString UROS2SISimulatorFeaturesMsg::MsgToString() const
{
    /* TODO: Fill here */
    checkNoEntry();
    return FString();
}
