// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from visualization_msgs/msg/UVCoordinate.msg - do not modify

#include "Msgs/ROS2UVCoordinate.h"

#include "Kismet/GameplayStatics.h"

void UROS2UVCoordinateMsg::Init()
{
    visualization_msgs__msg__UVCoordinate__init(&uv_coordinate_msg);
}

void UROS2UVCoordinateMsg::Fini()
{
    visualization_msgs__msg__UVCoordinate__fini(&uv_coordinate_msg);
}

const rosidl_message_type_support_t* UROS2UVCoordinateMsg::GetTypeSupport() const
{
    return ROSIDL_GET_MSG_TYPE_SUPPORT(visualization_msgs, msg, UVCoordinate);
}

void UROS2UVCoordinateMsg::SetMsg(const FROSUVCoordinate& Inputs)
{
    Inputs.SetROS2(uv_coordinate_msg);
}

void UROS2UVCoordinateMsg::GetMsg(FROSUVCoordinate& Outputs) const
{
    Outputs.SetFromROS2(uv_coordinate_msg);
}

void* UROS2UVCoordinateMsg::Get()
{
    return &uv_coordinate_msg;
}

FString UROS2UVCoordinateMsg::MsgToString() const
{
    /* TODO: Fill here */
    checkNoEntry();
    return FString();
}
