// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from simulation_interfaces/msg/Bounds.msg - do not modify

#include "Msgs/ROS2SIBounds.h"

#include "Kismet/GameplayStatics.h"

void UROS2SIBoundsMsg::Init()
{
    simulation_interfaces__msg__Bounds__init(&bounds_msg);
}

void UROS2SIBoundsMsg::Fini()
{
    simulation_interfaces__msg__Bounds__fini(&bounds_msg);
}

const rosidl_message_type_support_t* UROS2SIBoundsMsg::GetTypeSupport() const
{
    return ROSIDL_GET_MSG_TYPE_SUPPORT(simulation_interfaces, msg, Bounds);
}

void UROS2SIBoundsMsg::SetMsg(const FROSSIBounds& Inputs)
{
    Inputs.SetROS2(bounds_msg);
}

void UROS2SIBoundsMsg::GetMsg(FROSSIBounds& Outputs) const
{
    Outputs.SetFromROS2(bounds_msg);
}

void* UROS2SIBoundsMsg::Get()
{
    return &bounds_msg;
}

FString UROS2SIBoundsMsg::MsgToString() const
{
    /* TODO: Fill here */
    checkNoEntry();
    return FString();
}
