// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from example_interfaces/msg/MultiArrayLayout.msg - do not modify

#include "Msgs/ROS2MALayout.h"

#include "Kismet/GameplayStatics.h"

void UROS2MALayoutMsg::Init()
{
    example_interfaces__msg__MultiArrayLayout__init(&multi_array_layout_msg);
}

void UROS2MALayoutMsg::Fini()
{
    example_interfaces__msg__MultiArrayLayout__fini(&multi_array_layout_msg);
}

const rosidl_message_type_support_t* UROS2MALayoutMsg::GetTypeSupport() const
{
    return ROSIDL_GET_MSG_TYPE_SUPPORT(example_interfaces, msg, MultiArrayLayout);
}

void UROS2MALayoutMsg::SetMsg(const FROSMALayout& Inputs)
{
    Inputs.SetROS2(multi_array_layout_msg);
}

void UROS2MALayoutMsg::GetMsg(FROSMALayout& Outputs) const
{
    Outputs.SetFromROS2(multi_array_layout_msg);
}

void* UROS2MALayoutMsg::Get()
{
    return &multi_array_layout_msg;
}

FString UROS2MALayoutMsg::MsgToString() const
{
    /* TODO: Fill here */
    checkNoEntry();
    return FString();
}
